### ISSUE TITLE
Macros to help dispatch on VdafInstance

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1040]
We have a significant number of large match blocks that match on enums representing VDAFs. (Each arm constructs a struct that implements `Vdaf` from the enum variant's values, and then calls a generic ) With the generalization of CountVec into SumVec, and the possibility of maintaining PrgAes128-based VDAFs for special-case uses alongside the standardized PrgSha3-based VDAFs, these could all get bigger. I think we should probably write a small handful of declarative macros to generate these match blocks and get rid of some repetition.

I forget where I first saw this pattern, but I'm thinking of something like `vdaf_dispatch!(vdaf_instance, vdaf => {handle_request_generic(vdaf)?;})`. This could then expand into a match block, much like those we've written by hand. Each arm's block would first construct the VDAF, assign it to a let block with the identifier given in the pseudo-pattern, and then include the token stream for the block on the right of the `=>`.

Once the VDAF macro is in place, we may want to introduce another macro wrapping it to handle query types as well, but that may not be worth it, depending on how much code is query type-dependent.

**Comment by branlwyd** [comment]
I think we may want to handle query type too, we already have several blocks which dispatch based on both query type & VDAF.

**Comment by branlwyd** [comment]
(Though I wonder if we could have composable `query_type_dispatch!` and `vdaf_dispatch!` macros to make things easier -- I think it would likely work if we composed them to produce nested match blocks, and I suspect the optimizer is smart enough to generate the same code as if we wrote the nested match blocks as a single match block. I haven't tested that last bit, of course.)
