### ISSUE TITLE
Check whether garbage collection depends on invalid assumptions about aggregation jobs being many-to-one with collection jobs

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1061]
During [code review](https://github.com/divviup/janus/pull/1052#discussion_r1123566684), @divergentdave observed that it's incorrect to assume that in the case of time interval query tasks, an aggregation job belongs to exactly one collection. That used to be true, but it changed in #967.

I think that the query in `datastore::delete_expired_aggregation_artifacts` that determines whether aggregation jobs may be garbage collected (introduced in #961, just before #967) depends on that assumption. We should check whether the garbage collection implementation makes assumptions that were invalidated by #967 and fix them if so.

**Comment by branlwyd** [comment]
I think the GC logic is OK, because it is waiting to delete the aggregation job until all the underlying reports are ready for GC -- it doesn't need to care about which time interval/batch these reports are in, only the age of the reports & the configured maximum report age.

**Comment by branlwyd** [comment]
(I'm closing as I'm pretty sure the above argument holds water, but if anyone wants to provide a second set of eyes, please go ahead & reopen if necessary.)
