### ISSUE TITLE
Consider moving client out of server crate

### ISSUE THREAD

**Issue by cjpatton** [divviup/janus#116]
Janus has a client in a submodule of the `janus_server` create. In all likelihood, users may end up wanting the client code and not the server. It's a bit awkward to import this from a crate called `janus_server`.

Another option might be to rename the crate to simply `janus`.

**Comment by divergentdave** [comment]
Agreed, I think we will want a separate client crate. There is discussion of this in #18.

**Comment by cjpatton** [comment]
Ack, sorry for the dup.

**Comment by BranLwyd** [comment]
(closing as a duplicate of #18)

**Comment by tgeoghegan** [comment]
> Ack, sorry for the dup.

No need to apologize; duplicate feature requests or problem reports are valuable in that they can provide additional information on bugs and serve as an indicator of the severity of a problem or the level of interest in a feature.
