### ISSUE TITLE
Consider exposing `MockTime` in public API

### ISSUE THREAD

**Issue by cjpatton** [divviup/janus#117]
When setting up an integration test involving the Janus client, I found myself wanting to mock the current time. To do so I need to implement the `Clock` trait. As I went through this I basically found myself re-implementing `MockTime`, which is currently not available outside the crate. it would be super useful if you exposed this.

**Comment by BranLwyd** [comment]
This is coincidentally closed by https://github.com/divviup/janus/pull/118.

**Comment by tgeoghegan** [comment]
Closing per Brandon's last comment. Chris, please let us know if `time::test_util::MockClock` doesn't meet your needs.
