### ISSUE TITLE
Enum wrappers around generic request/response message types

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1231]
It might be worthwhile to introduce enum types that wrap the different possible specializations of our generic message types. (i.e. `AggregationJobInitializeReq<TimeInterval>` and `AggregationJobInitializeReq<FixedSize>`) This would let us be more rigorous about types in method signatures, rather than encoding to `Vec<u8>` before we leave match blocks. We could also use `MEDIA_TYPE` associated constants on the enum rather than `AggregationJobInitializeReq::<TimeInterval>::MEDIA_TYPE`.

**Comment by branlwyd** [comment]
I sorta disagree with this approach: this would incur some runtime cost where we currently lean on Rust's generics to handle things at compile time (albeit at the cost of larger code, probably). Especially for the "inner core" of Janus' aggregation, I would strongly prefer to keep things as generic as possible.

I'd suggest that if `Vec<u8>` handling is too painful (and I have no disagreement there), we should shift encoding up the call stack by refactoring the functions that currently return a `Vec<u8>` to instead be generic on (i.e.) query type & return the unencoded value instead. I think this is probably pretty easy especially now that we have pulled the task ID out of the messages, so we can determine the expected query type, VDAF, etc based on the task without needing to do any parsing.

I noticed the `MEDIA_TYPE` issue too -- it's somewhat unfortunate that you have to pick a specific set of type parameters for a generic type, even if the goal is to access a constant that does not depend on the type parameters. IMO, this doesn't motivate me to use dynamic dispatch, it motivates me to factor the `MEDIA_TYPE` constants out of the message types themselves (though, modulo this issue, I think they fit there pretty well).

**Comment by branlwyd** [comment]
I think we don't plan to implement this.
