### ISSUE TITLE
Opportunistic deletion of report shares

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1278]
It seems likely that database storage capacity will be the chief cost driver. We could reduce storage usage if we deleted report shares and preparation messages/shares once a report has been successfully aggregated and its query lifetime has been exhausted. Past that point, we only need to keep metadata about the report for some time, for anti-replay enforcement, until the report's timestamp is old enough that we can forget about the report entirely. This would reduce the amount of time for which we store the largest blobs, in the common case of successful aggregation and collection, in exchange for some additional writes. We could accomplish this either by overwriting report share columns, prepare state columns, and prepare message columns with NULL, or by separating report contents and report metadata into separate tables (similarly for report aggregation) and deleting rows from the table that holds the contents.

**Comment by branlwyd** [comment]
Current state of the blobs (roughly, encoded DAP/VDAF messages) we store:
* Reports (i.e. the `client_reports` table) are not opportunistically cleaned up.
* Aggregation state (i.e. the content of the `aggregation_jobs`, `report_aggregations` tables) are opportunistically cleaned up, at the point that the aggregation job goes to a final state.
* Collection state (i.e. the content of the `collection_jobs` & related tables) are not opportunistically cleaned up. But I don't think we want to clean these up: we need this data to service collection requests, even if they are repeated. That is, I think we can't clean this data up until it expires "naturally".
