### ISSUE TITLE
Deal with `tracing-stackdriver` dropping event fields whose labels contain `.`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1330]
> We should hold off on upgrading to this, as version 0.7.0 newly starts dropping event fields that contain a dot if the left side of the dot isn't recognized as a valid name for a nested object. See [this line](https://github.com/NAlexPear/tracing-stackdriver/blob/3f996f4aca1eb3e4e941283c4b8d9bb36efaa7af/src/visitor.rs#L77), introduced in NAlexPear/tracing-stackdriver#18. As an example, we do set fields with names [`report.task_id` and `report.metadata`](https://github.com/divviup/janus/blob/fa8a7f383cb79565c23607833d4b22eeb5336d1d/aggregator/src/aggregator.rs#L1052). I think we should first understand better how Cloud Logging handles these names, to understand what needs to change.

_Originally posted by @divergentdave in https://github.com/divviup/janus/issues/1314#issuecomment-1530226993_

**Comment by tgeoghegan** [comment]
For now, we won't take 0.7.x versions of `tracing-stackdriver`. Our paths forward here are to:

- see about getting a fix upstream
- revisit all our event fields to scrub `.` from them, perhaps by choosing a different separator.

**Comment by tgeoghegan** [comment]
See also https://github.com/divviup/janus/pull/1317

**Comment by divergentdave** [comment]
[Cloud Logging's rules for special fields](https://cloud.google.com/logging/docs/agent/logging/configuration#special-fields) say that any field that doesn't have special handling rules will be left alone as part of the `jsonPayload` attribute of a `LogEntry`. Moreover, `tracing-stackdriver 0.6.2` reformatted all fields except for `http_request` special fields to have camel case names, and this process treated periods as word boundaries. Thus, an upstream fix should be feasible, I've filed an issue for discussion. If not, we can replace periods with underscores; note that either `report.task_id` or `report_task_id` in the tracing event would both show up as `reportTaskId` in the log output.
