### ISSUE TITLE
Query mismatch errors

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1340]
Currently, `urn:ietf:params:ppm:dap:error:queryMismatch` is the one DAP error type Janus does not emit. This is technically a spec compliance issue, due to clauses like "Otherwise, the Helper MUST abort with error 'queryMismatch'." We may want to punt on it for a while, as fixing it would require either big changes to `janus_messages` or smuggling a sentinel inside `prio::codec::CodecError::Other`'s trait object.

**Comment by branlwyd** [comment]
I wonder if DAP should be modified to replace this with `invalidMessage` -- at least with our implementation strategy, getting a `queryMismatch` out of a decoding error will be somewhat awkward; and I'm having trouble imagining why a separate error code is required (the resulting aggregator behavior is the same, either way, and there are plenty of other possible message-parsing errors that do not get their own error code).

**Comment by branlwyd** [comment]
I sent https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/465 to remove `queryMismatch`, let's see what the editors think.

**Comment by tgeoghegan** [comment]
`queryMismatch` is long gone, so there's nothing left to do in this issue.
