### ISSUE TITLE
"self" aggregator URL is no longer used

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1368]
As of DAP-04, leader aggregators don't use their own endpoint URL anymore. Previously, this got used in collection job request responses in Location headers, and in problem document responses, before we aligned on the meaning of the `instance` attribute. We are also settling on only supporting a single helper aggregator.

We could change the internal representation of tasks to only store the peer aggregator's URL. This would simplify both the aggregator API and divviup-api by removing the need to pass both aggregators' URLs around when setting up tasks. Without such a change, one or both components will need to know the public URL of a deployment's own DAP endpoint in order to facilitate task setup.

Note that our integration tests rely on passing around both aggregator URLs in `Task` structures to configure the client. This could be easily replaced

**Comment by tgeoghegan** [comment]
I think this has been addressed in the work for #1524: we now have different `Task` and `AggregatorTask` structures to represent different views of a task. Is there more work we want to do here?

**Comment by tgeoghegan** [comment]
Closing, I don't think there's anything left to do here.
