### ISSUE TITLE
Integration test: improve method to wait for all reports to begin aggregation

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#1380]
Currently, the end-to-end integration test implementation in https://github.com/divviup/janus/blob/main/interop_binaries/tests/end_to_end.rs is racy: it expects that it can upload reports, then with no further synchronization or waiting submit a collection request, and have that collection request include all uploaded reports.

This is technically racy at time of writing: the query used to find collection jobs to process would allow a collection job to be processed even if there are reports that have not yet been added to an aggregation job at all -- I believe this test "worked" because the test's minimum batch size required all the reports to be aggregated for collection to succeed, and prior to #1354, there was nothing stopping an aggregation job from being created & processed concurrently with a collection job over the same batch.

This raciness will soon be more consequential: with #1354, once a collection request is received, no further aggregation jobs can be created if there is ever a point where there are no in-progress aggregation jobs. So unless the aggregation job creator "wins" the race against the collection job request, at least one report will never be aggregated, which will cause the test to fail.

This is worked around in #1354 by waiting (arbitrarily) 5 seconds after report uploads complete, before issuing a collection request. We should investigate a more robust fix, either by modifying our test's implementation or by modifying the semantics of the interop test API.

**Comment by divergentdave** [comment]
FWIW, very early versions of the interop test API had a `/advance_aggregation_collect_flows` endpoint, for similar purposes, but it was taken out for complexity and ease of implementation reasons.

**Comment by branlwyd** [comment]
Do you mean #1406? #1354's sleep did not affect the `janus_daphne` test.

**Comment by divergentdave** [comment]
Whoops, yes, #1406.

**Comment by branlwyd** [comment]
I have an idea for a non-sleep-based fix to the integration tests which might also improve behavior under "realistic" usage patterns, I'll see if it works out.

**Comment by branlwyd** [comment]
I suspect this is because we need a retry as in https://github.com/divviup/janus/blob/89f22b8455cc54a8c246fd286e9c10aa27696314/aggregator/src/aggregator/accumulator.rs#L173-L199 for initial batch writes -- if there isn't one, two aggregation jobs completing concurrently can cause one of the transaction writes to fail, and if the other aggregator does not implement idempotent requests, no further retries at the aggregation-job-step level will be possible.
