### ISSUE TITLE
Hide various test utilities needed by integration tests behind a feature

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#141]
We have a number of utilities to enable tests, such as `tests::test_util::MockClock` or methods on `datastore::Transaction` needed to fill databases with test data. Because we need to use some of these from integration test targets, we can't mark them `#[cfg(test)]` and instead resort to exporting them from the `janus_server` crate and marking them `#[doc(hidden)]` to discourage anything from using them. In #118, @BranLwyd had the idea of using a `test-utils` feature on the `janus_server` crate to ensure that only test configurations would compile in those utilities. Then we could have `janus_server`'s `[dev-dependencies]` or the `monolothic_integration_test` target enable that feature.

**Comment by tgeoghegan** [comment]
This is similar to how we handle the [`test-vector` feature in libprio-rs](https://github.com/divviup/libprio-rs/blob/662fc24a7df7c282fc2ad41c86442c4a8e7b7a80/Cargo.toml#L40).

**Comment by BranLwyd** [comment]
See also [`tokio`](https://crates.io/crates/tokio), which has a `test-util` feature that works similarly to how I expect our implementation would work.

**Comment by divergentdave** [comment]
As we split the codebase out into separate crates, we could also move some of these utilities into the test_utils crate. We could have that depend on the common crate. Then, if an item only depends on APIs in the common crate, and is only used in the server crate or other downstream crates, it could live in test_utils.
