### ISSUE TITLE
Make it easy to locally start a usable Janus pair

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1415]
We want it to be really easy to run a pair of Janus deployments locally and have them configured to run DAP aggregations together. This is valuable for developers, for integration testing, for teams evaluating how to operate Janus in their real infrastructure and to test things like task configuration.

It should be possible to `git clone` a fresh copy of Janus sources, then run a single command and the result should be a working pair of aggregators along with the necessary configuration information to start doing uploads. Something like:

```bash
> git clone git@github.com:divviup/janus.git
> cd janus
> ./run-aggregators
...
Aggregators are ready!
leader endpoint: http://localhost:8080
helper endpoint: http://localhost:8081
configured tasks:
- task ID: AAAAAAAAAAAAAAAA
  VDAF: Prio3Histogram
- task ID: BBBBBBBBBBBBBBBB
  VDAF: Prio3Sum
```

We have tools that do this in Divvi Up's deploy tools, which use Terraform to deploy Janus instances into [Kind](https://kind.sigs.k8s.io/) and then we run integration tests against that. However we have been reluctant to document those in public because we don't want downstream consumers of our Terraform modules.

At this point, there's enough interest from external teams working in Janus in running it locally that it's worth our time to solve this problem from this repository. Our plan is to start supporting a `docker-compose` setup for running a pair of Janus aggregators locally. We'll start using that to run integration tests here in the Janus repository.

**Comment by divergentdave** [comment]
Some relevant Docker Compose documentation:

[Share Compose configurations between files and projects](https://docs.docker.com/compose/extends/)

[Using profiles with Compose](https://docs.docker.com/compose/profiles/)

**Comment by inahga** [comment]
We more or less accomplished this in https://github.com/divviup/divviup-api/blob/main/compose.yaml. It's not perfect for a janus-only use case, but we've found it sufficient.
