### ISSUE TITLE
acquire_incomplete_aggregation_jobs() fails to find jobs too often

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1470]
During the most recent cloud-based load test, `acquire_incomplete_aggregation_jobs()` frequently returned zero jobs, though there were thousands of jobs meeting `state = 'IN_PROGRESS' AND lease_token IS NULL`. I had raised the log filter level on the job_driver module, so I can get a longitudinal view of job acquisition with this log explorer query:

```
resource.type="k8s_container"
jsonPayload.message="No jobs available" OR jsonPayload.message="Acquired jobs"
jsonPayload.target="janus_aggregator::binary_utils::job_driver"
```

Over two hours and 40 minutes, I see 32,951 "No jobs available" messages, and 2,791 "Acquired jobs" messages. There was a backlog of unprocessed jobs until the end of this timeframe, and the aggregation job drivers were overall falling behind, so this query is not performing as we wish.

**Comment by divergentdave** [comment]
This may or may not be related: I saw one instance of the following panic.

```
thread 'main' panicked at 'Acquired 24 jobs exceeding maximum of 4'
```

This never recurred, so it's a very rare problem, but it may help point to underlying problems in this query.

**Comment by divergentdave** [comment]
I have put together a single-process test harness to reproduce this issue, with all the same parameters. The code is on the [david/experiment-agg-job-test-harness branch](https://github.com/divviup/janus/compare/david/experiment-agg-job-test-harness), (see commit e14c86bbf53e5b40febc91cea1adb8bb9eb82cf2) and the command to run is `RUST_LOG=job_perf=info JANUS_INTEROP_CONTAINER=skip cargo test -p janus_integration_tests --test job_perf --release`. (Release builds are necessary to shard reports fast enough) This runs a leader aggregator, aggregation job creator, and aggregation job driver, a helper aggregator, and some client tasks for five minutes. The goal is that almost all aggregation jobs should be finished, and there should not be more than a couple incomplete aggregation jobs eligible for acquisition. I've found after running this several times that I typically get 40-60 in progress aggregation jobs, most of which are eligible for acquisition, though on occasion I see that all aggregation jobs are finished.

I tried moving the aggregation job subquery to a CTE, and that didn't work. Next up, I plan to [inspect the lock manager](https://www.postgresql.org/docs/15/view-pg-locks.html) periodically while the test is running, to see what's locking the aggregation_jobs table and its rows.

For reference here's a representative query plan.

```
Update on aggregation_jobs  (cost=15.14..23.41 rows=1 width=188)
  ->  Nested Loop  (cost=15.14..23.41 rows=1 width=188)
        ->  Nested Loop  (cost=14.99..23.07 rows=1 width=54)
              ->  HashAggregate  (cost=14.84..14.85 rows=1 width=40)
                    Group Key: "ANY_subquery".id
                    ->  Subquery Scan on "ANY_subquery"  (cost=0.16..14.84 rows=1 width=40)
                          ->  Limit  (cost=0.16..14.83 rows=1 width=20)
                                ->  LockRows  (cost=0.16..14.83 rows=1 width=20)
                                      ->  Nested Loop  (cost=0.16..14.82 rows=1 width=20)
                                            ->  Seq Scan on aggregation_jobs aggregation_jobs_1  (cost=0.00..11.38 rows=54 width=22)
                                                  Filter: ((lease_expiry <= '2023-06-23 18:03:40'::timestamp without time zone) AND (state = 'IN_PROGRESS'::aggregation_job_state))
                                            ->  Memoize  (cost=0.16..1.07 rows=1 width=14)
                                                  Cache Key: aggregation_jobs_1.task_id
                                                  Cache Mode: logical
                                                  ->  Index Scan using tasks_pkey on tasks tasks_1  (cost=0.15..1.06 rows=1 width=14)
                                                        Index Cond: (id = aggregation_jobs_1.task_id)
                                                        Filter: (aggregator_role = 'LEADER'::aggregator_role)
              ->  Index Scan using aggregation_jobs_pkey on aggregation_jobs  (cost=0.15..8.17 rows=1 width=30)
                    Index Cond: (id = "ANY_subquery".id)
        ->  Index Scan using tasks_pkey on tasks  (cost=0.15..0.33 rows=1 width=110)
              Index Cond: (id = aggregation_jobs.task_id)
```

**Comment by divergentdave** [comment]
> This may or may not be related: I saw one instance of the following panic.
> 
> ```
> thread 'main' panicked at 'Acquired 24 jobs exceeding maximum of 4'
> ```
> 
> This never recurred, so it's a very rare problem, but it may help point to underlying problems in this query.

I have found that by periodically running `ANALYZE aggregation_jobs` concurrently with everything else, I can reliably trigger this panic in the aggregation job driver.

**Comment by branlwyd** [comment]
This is a very interesting panic to me:

> thread 'main' panicked at 'Acquired 24 jobs exceeding maximum of 4'

The `max_acquire_count` value, which is concretely `4` in this panic, ultimately comes from https://github.com/divviup/janus/blob/38700aac7d7d64b8dfaae9d65979e8c433fbcaa7/aggregator/src/binary_utils/job_driver.rs#L135-L143 (generic job driver code).

The generic `run_job_acquisition` method calls into the aggregation-job-driver-specific lease acquiry code, which is https://github.com/divviup/janus/blob/38700aac7d7d64b8dfaae9d65979e8c433fbcaa7/aggregator/src/aggregator/aggregation_job_driver.rs#L840-L855.

The lease-acquiry code effectively just calls `acquire_incomplete_aggregation_jobs`, which runs a SQL query which (by my inspection) is limited to returning `max_acquire_count` rows, and produces one value in the result vector per returned row: https://github.com/divviup/janus/blob/38700aac7d7d64b8dfaae9d65979e8c433fbcaa7/aggregator_core/src/datastore.rs#L1799-L1862

A few thoughts:
(a) a second set of eyes on the relevant codepath & query is likely useful -- I don't see an obvious bug.
(b) it may be worthwhile to augment `acquire_incomplete_aggregation_jobs` with logging for both the value of `maximum_acquire_count` as well as the total number of rows returned from the query. This would rule out a bug in the query or its processing.
(c) it's interesting that this is triggered by `ANALYZE`. Outside of a (presumably very unlikely) issue in Postgres or `tokio-postgres`, this might indicate that the bug is triggered by some interaction with locking -- `ANALYZE` is documented as read-locking the table, and the relevant SQL query has `FOR UPDATE SKIP LOCKED`. However, I would expect this to lead to too few, rather than too many, rows.

**Comment by divergentdave** [comment]
I confirmed that the `maximum_acquire_count` argument going in is correct, and we're getting more than that many rows out of the query.

Here's an EXPLAIN ANALYZE plan I captured from one such incident, note that the top level node returned 22 rows.

<details><summary>Query plan</summary>

```json
{
  "Query Text": "UPDATE aggregation_jobs SET\n                    lease_expiry = $1,\n                    lease_token = gen_random_bytes(16),\n                    lease_attempts = lease_attempts + 1\n                FROM tasks\n                WHERE tasks.id = aggregation_jobs.task_id\n                AND aggregation_jobs.id IN (\n                    SELECT aggregation_jobs.id FROM aggregation_jobs\n                    JOIN tasks on tasks.id = aggregation_jobs.task_id\n                    WHERE tasks.aggregator_role = 'LEADER'\n                    AND aggregation_jobs.state = 'IN_PROGRESS'\n                    AND aggregation_jobs.lease_expiry <= $2\n                    FOR UPDATE SKIP LOCKED LIMIT $3\n                )\n                RETURNING tasks.task_id, tasks.query_type, tasks.vdaf,\n                          aggregation_jobs.aggregation_job_id, aggregation_jobs.lease_token,\n                          aggregation_jobs.lease_attempts",
  "Plan": {
    "Node Type": "ModifyTable",
    "Operation": "Update",
    "Parallel Aware": false,
    "Async Capable": false,
    "Relation Name": "aggregation_jobs",
    "Alias": "aggregation_jobs",
    "Startup Cost": 0.29,
    "Total Cost": 21.77,
    "Plan Rows": 1,
    "Plan Width": 188,
    "Actual Startup Time": 1.136,
    "Actual Total Time": 2.48,
    "Actual Rows": 22,
    "Actual Loops": 1,
    "Plans": [
      {
        "Node Type": "Nested Loop",
        "Parent Relationship": "Outer",
        "Parallel Aware": false,
        "Async Capable": false,
        "Join Type": "Semi",
        "Startup Cost": 0.29,
        "Total Cost": 21.77,
        "Plan Rows": 1,
        "Plan Width": 188,
        "Actual Startup Time": 0.198,
        "Actual Total Time": 1.116,
        "Actual Rows": 22,
        "Actual Loops": 1,
        "Inner Unique": false,
        "Join Filter": "(aggregation_jobs.id = \"ANY_subquery\".id)",
        "Rows Removed by Join Filter": 0,
        "Plans": [
          {
            "Node Type": "Nested Loop",
            "Parent Relationship": "Outer",
            "Parallel Aware": false,
            "Async Capable": false,
            "Join Type": "Inner",
            "Startup Cost": 0.15,
            "Total Cost": 8.21,
            "Plan Rows": 1,
            "Plan Width": 124,
            "Actual Startup Time": 0.082,
            "Actual Total Time": 0.143,
            "Actual Rows": 22,
            "Actual Loops": 1,
            "Inner Unique": true,
            "Plans": [
              {
                "Node Type": "Seq Scan",
                "Parent Relationship": "Outer",
                "Parallel Aware": false,
                "Async Capable": false,
                "Relation Name": "aggregation_jobs",
                "Alias": "aggregation_jobs",
                "Startup Cost": 0,
                "Total Cost": 0,
                "Plan Rows": 1,
                "Plan Width": 30,
                "Actual Startup Time": 0.046,
                "Actual Total Time": 0.056,
                "Actual Rows": 22,
                "Actual Loops": 1
              },
              {
                "Node Type": "Index Scan",
                "Parent Relationship": "Inner",
                "Parallel Aware": false,
                "Async Capable": false,
                "Scan Direction": "Forward",
                "Index Name": "tasks_pkey",
                "Relation Name": "tasks",
                "Alias": "tasks",
                "Startup Cost": 0.15,
                "Total Cost": 8.17,
                "Plan Rows": 1,
                "Plan Width": 110,
                "Actual Startup Time": 0.003,
                "Actual Total Time": 0.003,
                "Actual Rows": 1,
                "Actual Loops": 22,
                "Index Cond": "(id = aggregation_jobs.task_id)",
                "Rows Removed by Index Recheck": 0
              }
            ]
          },
          {
            "Node Type": "Subquery Scan",
            "Parent Relationship": "Inner",
            "Parallel Aware": false,
            "Async Capable": false,
            "Alias": "ANY_subquery",
            "Startup Cost": 0.15,
            "Total Cost": 13.53,
            "Plan Rows": 1,
            "Plan Width": 40,
            "Actual Startup Time": 0.037,
            "Actual Total Time": 0.037,
            "Actual Rows": 1,
            "Actual Loops": 22,
            "Plans": [
              {
                "Node Type": "Limit",
                "Parent Relationship": "Subquery",
                "Parallel Aware": false,
                "Async Capable": false,
                "Startup Cost": 0.15,
                "Total Cost": 13.52,
                "Plan Rows": 1,
                "Plan Width": 20,
                "Actual Startup Time": 0.036,
                "Actual Total Time": 0.036,
                "Actual Rows": 1,
                "Actual Loops": 22,
                "Plans": [
                  {
                    "Node Type": "LockRows",
                    "Parent Relationship": "Outer",
                    "Parallel Aware": false,
                    "Async Capable": false,
                    "Startup Cost": 0.15,
                    "Total Cost": 13.52,
                    "Plan Rows": 1,
                    "Plan Width": 20,
                    "Actual Startup Time": 0.036,
                    "Actual Total Time": 0.036,
                    "Actual Rows": 1,
                    "Actual Loops": 22,
                    "Plans": [
                      {
                        "Node Type": "Nested Loop",
                        "Parent Relationship": "Outer",
                        "Parallel Aware": false,
                        "Async Capable": false,
                        "Join Type": "Inner",
                        "Startup Cost": 0.15,
                        "Total Cost": 13.51,
                        "Plan Rows": 1,
                        "Plan Width": 20,
                        "Actual Startup Time": 0.005,
                        "Actual Total Time": 0.027,
                        "Actual Rows": 12,
                        "Actual Loops": 22,
                        "Inner Unique": true,
                        "Plans": [
                          {
                            "Node Type": "Seq Scan",
                            "Parent Relationship": "Outer",
                            "Parallel Aware": false,
                            "Async Capable": false,
                            "Relation Name": "aggregation_jobs",
                            "Alias": "aggregation_jobs_1",
                            "Startup Cost": 0,
                            "Total Cost": 0,
                            "Plan Rows": 1,
                            "Plan Width": 22,
                            "Actual Startup Time": 0.002,
                            "Actual Total Time": 0.006,
                            "Actual Rows": 12,
                            "Actual Loops": 22,
                            "Filter": "((lease_expiry <= $2) AND (state = 'IN_PROGRESS'::aggregation_job_state))",
                            "Rows Removed by Filter": 0
                          },
                          {
                            "Node Type": "Index Scan",
                            "Parent Relationship": "Inner",
                            "Parallel Aware": false,
                            "Async Capable": false,
                            "Scan Direction": "Forward",
                            "Index Name": "tasks_pkey",
                            "Relation Name": "tasks",
                            "Alias": "tasks_1",
                            "Startup Cost": 0.15,
                            "Total Cost": 8.17,
                            "Plan Rows": 1,
                            "Plan Width": 14,
                            "Actual Startup Time": 0.001,
                            "Actual Total Time": 0.001,
                            "Actual Rows": 1,
                            "Actual Loops": 253,
                            "Index Cond": "(id = aggregation_jobs_1.task_id)",
                            "Rows Removed by Index Recheck": 0,
                            "Filter": "(aggregator_role = 'LEADER'::aggregator_role)",
                            "Rows Removed by Filter": 0
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}
```

</details>

**Comment by divergentdave** [comment]
I usually see the entire subquery, "Limit" included, rolled up into a HashAggregate node, in the outer loop of two nested loop joins with aggregation_jobs/tasks. In this case, when we got too many rows, the subquery became the inner loop of a nested loop join, and the "Limit" node ran for 22 loops, returning one row each time. This suggests to me that either the guarantees of `LIMIT` inside a subquery aren't as strong as we thought they were, or we may have run across a query planner bug.

We could likely resolve this panic by moving the subquery to a CTE. (I experimented with this previously for performance reasons, and didn't notice a difference, but it now seems worth doing for correctness) This would force Postgres to materialize one set of ten locked job rows, rather than repeatedly evaluating the subquery and taking one row each time. This section of the "WITH Clause" documentation seems particularly promising:

> A key property of WITH queries is that they are normally evaluated only once per execution of the primary query, even if the primary query refers to them more than once. In particular, data-modifying statements are guaranteed to be executed once and only once, regardless of whether the primary query reads all or any of their output.

**Comment by divergentdave** [comment]
I have a promising mechanism to explain this issue, our queries that take explicit row locks are also locking rows in the tasks table. The [locking clause documentation](https://www.postgresql.org/docs/current/sql-select.html#SQL-FOR-UPDATE-SHARE) says "A locking clause without a table list affects all tables used in the statement." We have three different queries with `FOR UPDATE SKIP LOCKED`, each joining a different table to `tasks`, used by the aggregation job creator, aggregation job driver, and collection job driver. Thus, the different components could prevent this query from finding any tasks, and in turn finding any aggregation jobs, by contending on the tasks rows. This would get worse as we ran more instances of these three components.

I repeatedly scanned `pgrowlocks('tasks')`, and confirmed that "For Update" mode row locks are being taken in the tasks table, and that the backends holding the locks were servicing connections from the aggregation job creator and aggregation job driver. (I am not running the collection job driver in my test harness) There's no other reason for queries to be locking these rows, since the tasks are write-once.
