### ISSUE TITLE
Constrain collect requests to non-overlapping batch intervals

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#149]
We know that the current specification on batch parameter validation is inadequate. That problem in DAP is tracked in https://github.com/ietf-wg-ppm/ppm-specification/issues/195. In the meantime, our objective is to implement the collect requirements that are currently spelled out. However, @BranLwyd points out [in this PR comment](https://github.com/divviup/janus/pull/142#discussion_r866506165) that there are some obvious attacks that we should mitigate before we consider handling real user data with Janus, even if the language in DAP isn't finalized.

**Comment by BranLwyd** [comment]
Thinking about this some more, another option might be to get informed consent from the folks collecting the data. OTOH, the collector is the attacker in this scenario, so maybe we'd want to tell the end-users instead--but I'm not sure how we'd communicate an issue of this level of technical complexity to the end-users whose data is being collected.

**Comment by BranLwyd** [comment]
https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/277 is a (possibly-temporary) fix to this privacy problem in DAP, requiring collect requests to refer to non-overlapping batch intervals. As this change has been committed to the DAP spec, we need to update Janus to follow this requirement.

Marking with interop-testing as this will be required for DAP-01 compliance.
