### ISSUE TITLE
Consider using PostgreSQL's `tsrange`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#150]
PostgreSQL has [range types](https://www.postgresql.org/docs/current/rangetypes.html), which among other things allow columns to represent a range of times. Ranges come with handy operators like `<@` that let you test whether a range contains another range or if a range contains a value. We could use `tsrange` ("range of timestamp without time zone") in tables like `aggregate_share_jobs` in lieu of storing `batch_interval_start` and `batch_interval_duration` as `TIMESTAMP` and `BIGINT`, respectively, which would make it easier to write some queries and (I think/hope) let us create efficient indices on the ranges.

**Comment by divergentdave** [comment]
This was completed in #255.
