### ISSUE TITLE
`test_util` is maybe too generic a name for a crate

### ISSUE THREAD

**Issue by cjpatton** [divviup/janus#151]
This matters when attempting to use the `define_ephemeral_datastore` macro. I would like to rename this to something like `janus_test_util`, but the macro expects `test_util`:

```
  --> tests/janus.rs:12:1
   |
12 | janus_test_util::define_ephemeral_datastore!();
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in the macro `janus_test_util::define_ephemeral_datastore` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
   |
5  | use janus_server::datastore::Datastore;
```

Any chance of renaming this to something more distinguished?

**Comment by BranLwyd** [comment]
@cjpatton The crate formerly known as `test_util` is now named `janus_test_util`.
