### ISSUE TITLE
Collapse `task_vdaf_verify_keys`, `task_collector_auth_tokens`, `task_aggregator_auth_tokens` tables into `tasks`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1521]
As of DAP-04, task parameters like the VDAF verify key are immutable and cannot be rotated (save by creating a new task). Janus' DB schema has separate tables `task_vdaf_verify_keys`, `task_collector_auth_tokens` and `task_aggregator_auth_tokens` with foreign keys into `tasks` to allow many:1 relationships, but simplify the schema if a task is only ever going to have a single verify key, auth token, etc.

**Comment by branlwyd** [comment]
VDAF verify keys are immutable, but it's not necessarily true that the implementation-specific collector/aggregator auth tokens need to be. OTOH, since rotating VDAF verify keys requires task rotation, maybe we decide it's OK to require task rotation for rotating other kinds of secrets.

**Comment by tgeoghegan** [comment]
See discussion in #1509: if we choose to enable aggregator or collector auth token rotation, then we will still need the many tokens:1 task relationship for those two things.
