### ISSUE TITLE
Add index on `collection_jobs.collection_job_id`.

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#1550]
Currently, none of the indexes on `collection_jobs` refers to `collection_job_id`. But e.g. `get_collection_job` (and perhaps other operations) do lookups by collection job ID. I suspect this means retrieving a collection job by ID is currently a table-scan (have not analyzed); this will likely impact scalability for larger deployments and should be fixed.

**Comment by branlwyd** [comment]
(while we're at it, all of the existing collection job getters take a collection job ID only, rather than a task ID & collection job ID. to ensure isolation between tasks, we should update them to take & use a task ID too -- so the index would be on `(task_id, collection_job_id)`.)

**Comment by divergentdave** [comment]
We currently have a `UNIQUE` index covering `collection_job_id`. #1878 took care of adding a task_id argument to `get_collection_job()`. We don't yet have an index covering both columns.
