### ISSUE TITLE
Adopt `tokio-rs/tracing`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#16]
[`tokio-rs/tracing`](https://github.com/tokio-rs/tracing) and friends are really great ways to log structured events. We should use them in Janus server. There's some [prior art in `ppm-prototype`](https://github.com/abetterinternet/ppm-prototype/blob/main/src/trace.rs), though we should invest some more effort:

- We want to pretty-print events to stdout or stderr when running in a tty, but we want to log structured JSON objects when running in a cloud so they can be indexed by a log searching product
- We should judiciously create and annotate tracing spans so that we can selectively set log levels on different modules

**Comment by divergentdave** [comment]
FYI, I noticed that `tracing-error` currently does not have any effect in `prio-server` or `ppm-prototype`. The `ErrorLayer` is added to the subscriber registry, but no `SpanTrace` objects are ever constructed directly or via `TracedError`, to capture span information for later display.

:+1: on `tracing` generally, it's got a great reputation.

**Comment by divergentdave** [comment]
We will likely want to use [tracing-log](https://docs.rs/tracing-log/latest/tracing_log/) so that dependencies using the log facade can be brought in to our tracing subscribers. `tracing_log::LogTracer` can act as the default logger, and forward log messages as (unstructured) tracing events within the current span.

**Comment by divergentdave** [comment]
We have the tracing infrastructure mostly set up at this point. Next up, after implementing the rest of the routes, we should annotate the spans defined by `warp::filters::trace::named()` with appropriate per-request fields.

**Comment by tgeoghegan** [comment]
I think we've got everything we want implemented and hooked up. Specific issues (like tweaking the JSON output to work well with GCP logging) are tracked elsewhere. Closing this; we can re-open if this still tracks anything valuable.
