### ISSUE TITLE
Unnecessary check in `step_aggregation_job` for fixed-size tasks

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#1623]
https://github.com/divviup/janus/blob/d46f047622ef68b871b0a0eb69a987ddb4edc8db/aggregator/src/aggregator/aggregation_job_continue.rs#L85-L104 checks that a report share in an aggregate share job does not intersect in time with any existing aggregate share jobs. This check is not necessary for fixed-size tasks, and should be factored out to an `AccumulableQueryType` method.

Since the check is implemented by checking against `aggregate_share_jobs.batch_interval`, which will always be `NULL` for fixed-size tasks, this does not constitute a functional problem -- only an unnecessary DB query per aggregation step.

**Comment by inahga** [comment]
I believe this has been accomplished as part of `AggregationJobWriter` refactors a while ago. We now have a flag that tracks whether a batch is accepting aggregations or not.
