### ISSUE TITLE
Auth tokens are confusing

### ISSUE THREAD

**Issue by simon-friedberger** [divviup/janus#1645]
It seems the HTTP API will return JSON with e.g. 
```json
"collector_auth_token": "YmY5ZTgzM2Y2YTA0OGNkNWI3ZGE2NDhjYzk3YWFiNWQ",
```
which doesn't specify if it's a bearer token or dap-auth-token and doesn't include the required padding.
```py
headers = { "Authorization": "Bearer YmY5ZTgzM2Y2YTA0OGNkNWI3ZGE2NDhjYzk3YWFiNWQ=",
#headers = { "Authorization": "Bearer YmY5ZTgzM2Y2YTA0OGNkNWI3ZGE2NDhjYzk3YWFiNWQ", # does not work
#headers = { "DAP-Auth-Token": "YmY5ZTgzM2Y2YTA0OGNkNWI3ZGE2NDhjYzk3YWFiNWQ=", # does not work
```

**Comment by divergentdave** [comment]
On more recent versions, the HTTP API will return a JSON object with "type" and "token" fields. The token is also transmitted with the correct padding. This was fixed in #1388.
