### ISSUE TITLE
Allow lookup of collection jobs by query and aggregation parameter

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1655]
DAP makes the collector responsible for choosing collection job IDs ([1](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-05#name-collection-job-initializati)). To poll collection job status and eventually obtain aggregate shares, the collector must keep track of the IDs it has chosen, and more to the point the mapping of collection job IDs to the query (e.g., an interval of time). Neither DAP nor Janus provide a means of discovering what collection jobs exist for a task, nor checking whether a collection job exists for some query and aggregation parameter.

The DAP API makes it the collector's responsibility to choose collection job IDs for two reasons:

- Consistency with the aggregation job API
- Collection job ID is an obvious idempotency key for the `PUT /tasks/{task-id}/collection_jobs/{collection-job-id}` endpoint

However, the fields of [`CollectionReq`](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-05#section-4.6.1-6) (namely the query and the aggregation parameter) are sufficient to uniquely identify a collection job. The collector has no choice but to keep track of those values, so collection job interfaces that operate on those would reduce the statefulness of collector implementations.

It's possible that DAP should revisit the design of the collection job API, but as a step in that direction, we could add a end API endpoint to Janus:

`QUERY /tasks/{task-id}/collection_jobs`

We use the [HTTP QUERY method](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html), which is just GET but with a request body. The body would be a `CollectionReq`. If some collection job exists in the task that matches the `CollectionReq`, then the response is HTTP 302 Found with a `Location` header containing the full collection job ID (i.e., `https://dap.example.org/tasks/{task-id}/collection_jobs/{collection-job-id}`.

We could also provide an endpoint that enumerates all available collection jobs in a task (something like `GET /tasks/{task-id}/collection_jobs`).

**Comment by tgeoghegan** [comment]
@simon-friedberger this issue is based on our discussion yesterday. Please let me know what you think!

**Comment by simon-friedberger** [comment]
The trigger for this was that it was previously possible to repeatedly query a specific time interval. Since the query is theoretically idempotent, this seems reasonable. But that's not possible with the current API because the Collector has to create a new collection job. This seems to fail because it creates another aggregation job and we currently always limit those with `max_batch_query_count = 1`.

So, I think the right thing to do here would be to just allow the collector to return the same result again (without aggregating again). Afaict this change wasn't prompted by a change in the standard.

**Comment by branlwyd** [comment]
#1799 will restore the ability to repeatedly query a specific time interval. @simon-friedberger, with that in mind, is the API proposed by this issue still valuable?

I have some concerns about exposing this custom API -- I believe a Collector implementation would still need to track some per-collection data to ensure it polls all collections to completion, writes collection results to post-DAP durable storage, etc.

**Comment by branlwyd** [comment]
Per Simon's comment, closing this issue -- I think we no longer have motivation to implement the collection-job-search/list APIs suggested by this issue's OP.

Simon, FWIW/informationally, one more way to deal with this problem (even without #1799) would be for the Collector to write down the collection ID/batch ID/aggregation param to its durable storage before making a collection request; then, if the Collector restarted, it would be able to retry an identical request by rereading its durable storage. Of course, with #1799, this is no longer necessary.
