### ISSUE TITLE
Upgrade to 0.20 release of opentelemetry-rust

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1657]
This issue tracks upgrading all crates from the opentelemetry-rust ecosystem for their 0.20 release.

- [opentelemetry 0.20.0](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0200)
- [opentelemetry_api 0.20.0](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-api/CHANGELOG.md#v0200)
  - We no longer need to pass `&Context::current()` to instruments (counters, gauges, and histograms).
- [opentelemetry_sdk 0.20.0](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/CHANGELOG.md#v0200)
  - There is now a per-instrument cardinality limit of 2000 data points. This should mitigate any future high-cardinality label bugs. We could alert on this with the PromQL expression `{otel_metric_overflow=~".+"}`.
  - There is a new `InMemoryMetricsExporter` that we could use going forward in metrics-related testing. This would be easier to use than iterating over everything via `BasicController`.
  - There were many metrics SDK breaking changes, due to OpenTelemetry spec changes.
  - There is a new `DefaultAggregatorSelector`, and it includes some default histogram boundaries. (We'll still want to use our customized boundaries from our own implementation of the trait)
- [opentelemetry-semantic-conventions 0.12.0](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-semantic-conventions/CHANGELOG.md#v0120)
- [opentelemetry-prometheus 0.13.0](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-prometheus/CHANGELOG.md#v0130)
  - The conversion between OpenTelemetry units and Prometheus units changed, and Prometheus metric names will now include a unit suffix, following Prometheus naming conventions. We will need to take units out of the names we pass in to OpenTelemetry, and check to see if we need to change any dashboards.
  - Exporter configuration has three new options, `with_namespace` (to add a prefix to Prometheus metrics names), `without_units`, and `without_counter_suffixes`.
- [opentelemetry-proto 0.3.0](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/CHANGELOG.md#v030)
- [opentelemetry-otlp 0.13.0](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/CHANGELOG.md#v0130)
  - Aggregation selectors and temporality selectors are now optional when constructing exporters.
- [tracing-opentelemetry 0.20.0](https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/CHANGELOG.md#0200-august-1-2023)
- [trillium-opentelemetry 0.3.0](https://github.com/trillium-rs/trillium-opentelemetry/releases/tag/v0.3.0)

**Comment by branlwyd** [comment]
https://github.com/divviup/janus/pull/1664 handles most of this except, but still needs at least:

1) `tracing-opentelemetry` to be updated.
2) Metric name updates for `opentelemetry-prometheus`

(both as mentioned in the OP)

**Comment by divergentdave** [comment]
There's now a tracing-opentelemetry release: https://crates.io/crates/tracing-opentelemetry/0.20.0

**Comment by branlwyd** [comment]
(I'll have time to work on this in a ~week or so, I think this is not so urgent that it can't wait that long; if that's incorrect, let's handoff.)

**Comment by tgeoghegan** [comment]
The fix here will need to be merged to:

- `release/0.subscriber-01`
- `release/0.5`
- `main`

**Comment by branlwyd** [comment]
All relevant versions of Janus have had their `opentelemetry`-related crates updated.
