### ISSUE TITLE
aggregator API: don't return HTTP error when deleting resource that doesn't exist

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1691]
The aggregator API's endpoints for DELETE-ing resources return HTTP 204 No Content if a resource was successfully deleted, but HTTP 404 Not Found if the resource in question didn't already exist. For idempotence reasons, I think both cases should return HTTP 204 No Content because regardless of whether the resource existed, the client's desired postcondition is achieved. Returning distinct HTTP status codes just makes clients more complicated, because I doubt they'll do anything different if they get 404 instead of 204.

**Comment by inahga** [comment]
Resolved by https://github.com/divviup/janus/pull/1694
