### ISSUE TITLE
`0.subscriber-01`: remove blind sleep from fixed-size end-to-end test

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#1727]
Currently, the end-to-end test for fixed-size queries in `0.subscriber-01` contains a blind sleep: https://github.com/divviup/janus/blob/6e874b7c175e4eda981c7f5de4d79155d63a190f/integration_tests/tests/common/mod.rs#L228-L232

This sleep exists to give the aggregation job creator enough time to create aggregation jobs for all of the incoming reports; if the sleep is not there, the attempt to create a collection job will fail with `invalidBatchSize`.

This sleep should be changed into a poll-loop that waits for the batch to become collectable, most likely by retrying on `invalidBatchSize` errors.

**Comment by inahga** [comment]
We have abandoned this branch of Janus.
