### ISSUE TITLE
`release/0.subscriber-01`: trim unneeded features

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1728]
We drop support for the `l2_fixedpoint` stuff in https://github.com/divviup/janus/pull/1695 because we know that deployment will never need it. In the interest of reducing maintenance costs, we might consider dropping other unneeded features as the exact requirements of that deployment come into focus. For instance, we may be able to drop one of the query types or some more VDAFs, which would reduce the amount of code we carry around in `release/0.subscriber-01`. Then again, it might make it harder to apply patches across release branches.

**Comment by branlwyd** [comment]
Once we know more about the operational configuration we'll be using, we may be able to drop a query type, too, to save quite a bit of code.

**Comment by branlwyd** [comment]
I think this is wise. We're going to be viewing this as effectively a custom deployment, so we can trim anything that isn't actively used by the deployment.

At least for VDAFs/query types, I think merge issues when doing patches won't be too bad -- almost all of the "complex" code is parameterized by VDAF/query-type; it won't be too hard to fixup merge issues on our VDAF/query-type dispatch code.

**Comment by inahga** [comment]
We have abandoned this branch of Janus.
