### ISSUE TITLE
Janus' new MSRV policy

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1730]
Janus transitively depends on crate `time`, which has a [new MSRV policy](https://github.com/time-rs/time/discussions/535) of supporting the last two production Rust toolchain releases. That means that's now our MSRV policy. We should implement this policy in our CI actions and document it in the README.

**Comment by tgeoghegan** [comment]
https://github.com/dtolnay/rust-toolchain#toolchain-expressions should make this easy: we can just do:
```
with:
      toolchain: stable minus 2 releases
```

**Comment by divergentdave** [comment]
Done in #1848 and friends.
