### ISSUE TITLE
Aggregation/collect job queuing behavior

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#174]
In #167, the aggregation job driver queries the `aggregation_jobs` table to find work to schedule, meaning that this table is a job queue. At the moment, the query against the queue uses a `LIMIT` clause, and if we `ORDER BY` job ID, then we get a LIFO queue (because the query will yield the newest `aggregation_jobs` rows).

We should decide what queuing behavior we want. Maybe we want a FIFO rather than a LIFO. We also may want to de-prioritize sufficiently old aggregation jobs, on the premise that newer ones are more interesting to the collector.  I think that means `aggregation_jobs` would need a column for insertion timestamp. 

We should also teach `aggregation_job_driver` to detect when an incomplete aggregation jobs should be abandoned because a collect job has already run for the batch interval in which the aggregation jobs' reports fall, and thus no further reports should be accumulated

**Comment by BranLwyd** [comment]
https://medium.com/swlh/fifo-considered-harmful-793b76f98374 & https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.376.5966&rep=rep1&type=pdf make a case for LIFO behavior in our queue-processing.

**Comment by BranLwyd** [comment]
We should also decide what we want to FIFO on. #167 FIFOs on order-of-aggregation-job-creation. But we might plausibly instead want to FIFO on time-of-last-step.

**Comment by BranLwyd** [comment]
This bug also applies to the collect job driver queuing behavior.

**Comment by tgeoghegan** [comment]
We may make changes to queueing behavior or implementation in response to specific scenarios we encounter, but this issue doesn't discuss anything actionable.
