### ISSUE TITLE
Metrics for GC

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1740]
We should add some metrics to the GC component for use in monitoring and alerting. We'll need a status counter with success and error label values to record the outcome of `gc_task()` calls. We could also record the number of each kind of artifact deleted with some small changes.

**Comment by tgeoghegan** [comment]
We now have a really nice GC dashboard in Grafana. Are we still missing any valuable metrics? @divergentdave @inahga

**Comment by divergentdave** [comment]
I don't think we implemented the first idea, but we do now have charts that filter transaction success/failure metrics to the garbage collection transaction, which is good enough IMO. Counters for deleted reports are done. LGTM, closing.
