### ISSUE TITLE
Move unit tests to separate module files

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1795]
We have four different integration test targets inside `janus_integration_tests`. Per ["Delete Cargo Integration Tests" by matklad](https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html) we could rearrange these into one target, and save significant time in the linker. (Note this will require a lockstep update with the `test_command` used in janus-ops)

**Comment by tgeoghegan** [comment]
This is a great idea. While we're at it, we should apply [another recommendation](https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html#Assorted-Tricks) from matklad, which is to move ordinary unit tests into their own files (we've been trending in this direction already). This helps limit the growth of source files but also should prevent needless recompilation of non-test code, which I think will help speed up everyone's `rust-analyzer`.

**Comment by divergentdave** [comment]
Regarding moving integration tests to separate files, rust-analyzer has an assist called "Extract module to file" that can speed this up.

**Comment by branlwyd** [comment]
We should continue to do this on an as-needed basis, but most modules with a large number of unit tests now use a separate file for tests.
