### ISSUE TITLE
Collector API redesign

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1796]
We will need to make the API of `janus_collector` more flexible in order for it to be used in stateful collector services, and recover from errors or downtime without unnecessarily losing data. Since draft-ietf-ppm-dap-04, collectors can no longer "rediscover" collection jobs by sending the same collection request multiple times, which makes the limitations of the current API worse.

The simplest straw man proposal to achieve this would be making the `janus_collector::CollectionJob` struct public, implementing `serde::Serialize` and `serde::Deserialize` on it, and making the methods `Collector::start_collection()` and `Collector::poll_once()`/`Collector::poll_until_complete()` public. This would allow consumers to save the collection job ID (along with other necessary parameters) and query it later beyond the scope of one Rust future.

Exposing a collection job structure would also let us address #762, adding an API to delete a collection job.

Per #1655, it would be natural to return a collection job structure when querying existing collection jobs by query with a Janus-specific API.

This would be good take care of before we cut 0.6.0.

**Comment by branlwyd** [comment]
Exposing the collection job as part of the API is a good idea, and something like it is required to make a collector work out.

One question:

> Since draft-ietf-ppm-dap-04, collectors can no longer "rediscover" collection jobs by sending the same collection request multiple times,

Why not? I quickly scanned the diff between -03 & -04 and didn't spot anything -- I think resending the same collection request multiple times should be supported, and it's likely a spec bug if it is not supported.

**Comment by divergentdave** [comment]
This is because of the problem described in #1655, we switched from the leader choosing collect URIs to the collector choosing collection job IDs. Note that sending the same collection request with the same collection job ID is idempotent, but if you forget the ID and remember the collection request, sending the same request under a fresh collection job ID results in Janus returning a "batch collected too many times" error.

**Comment by branlwyd** [comment]
Ah, fair -- I think that can be worked around by having the collector store the collection job ID to durable storage before sending it the first time. (This would imply `janus_collector` taking a caller-provided `CollectionJobId` when starting a collection, rather than determining one randomly -- this may be what you had in mind already.)

**Comment by branlwyd** [comment]
Thinking about this a little more, this issue mostly affects time-interval: the idea for fixed-size w/ a `current_batch` query is that the first poll of a collection job is when the set of outstanding batches changes (see https://www.ietf.org/archive/id/draft-ietf-ppm-dap-05.html#name-a-note-on-idempotence). So for `current_batch` queries, it's totally OK for a collector to fire-and-forget a given collection job ID; no batch will be lost.

Of course, if a `by_batch_id` query is made, we have a similar issue regarding lost collection job IDs, so this problem isn't entirely solved by fixed-size (at least for VDAFs requiring multiple aggregations).
