### ISSUE TITLE
Proposed crate/directory layout

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#18]
Now that we are building client, server, and common PPM components, I thought it would be good to reorganize them into separate crates. How does this look?

Before:
```
├── .github ...
├── .gitignore
├── janus_server
│   ├── Cargo.lock
│   ├── Cargo.toml
│   ├── src
│   │   ├── aggregator.rs
│   │   ├── bin
│   │   │   └── aggregator.rs
│   │   ├── client.rs
│   │   ├── hpke.rs
│   │   ├── lib.rs
│   │   └── message.rs
│   └── tests
│       └── integration_test.rs
├── LICENSE
└── README.md
```

After:
```
├── .github ...
├── .gitignore
├── Cargo.lock
├── Cargo.toml (workspace only)
├── LICENSE
├── README.md
├── janus
│   ├── Cargo.toml
│   ├── src
│   │   ├── lib.rs
│   │   ├── hpke.rs
│   │   └── message.rs
│   └── tests
├── janus_client
│   ├── Cargo.toml
│   ├── src
│   │   └── lib.rs
│   └── tests
│       └── integration_test.rs
└── janus_server
    ├── Cargo.toml
    ├── src
    │   ├── aggregator.rs
    │   ├── bin
    │   │   └── aggregator.rs
    │   └── lib.rs
    └── tests
        └── integration_test.rs
```

**Comment by BranLwyd** [comment]
Sure, this layout seems reasonable.

Can we get away with doing this lazily? e.g. for now, write code into `janus_server` specifically. Then as we move into the client implementation, factor the things we need out of `janus_server` to a common `janus` crate. I only suggest this because factorings like this tend to work out better if they are based on a concrete need rather than our best guesses as to what will need to be factored where, though admittedly `hpke.rs` and `message.rs` will pretty clearly be needed in both a client & server.

**Comment by tgeoghegan** [comment]
In #37, I add dependencies on `structopt` and `serde_yaml` to `janus_server` that I think aren't necessarily needed in the library crate. The former is only needed in the `aggregator` bin and the latter could be in `dev-dependencies` but for the binary target. If we split out the binaries into their own crate in the workspace proposed here, I think we could distinguish between things that `janus_server` needs and that its binaries need. Or is Rust dead code detection already smart enough to deal with this for us?

**Comment by divergentdave** [comment]
On the subject of crate layout, there's a long-open issue against Cargo that notes that crates cannot be published to crates.io if there is a cycle in their dev-dependencies. (Note that cycles in non-dev dependencies are categorically not allowed by Cargo, as there's no way to build them) As such, I think we may want to move integration tests that use our client and server types in the same process to a fourth crate. This way, our dependency tree will be a diamond-shaped DAG, even including dev-dependencies.

**Comment by divergentdave** [comment]
I did some rough prototyping of splitting out janus and janus_client crates. As a prerequisite, we will need to clean up the API for a number of structs, replacing `pub(crate)` member accesses with constructors and getters.

- Add/use `.as_bytes()` on `TaskId` and `AggregationJobId`.
- Expose conversion methods to go between `Time` and `NaiveDateTime` or `u64` timestamps.
- Make `Time::is_after()` public.
- Add `Duration::as_seconds()`, returning a `u64`.
- Make most methods of `Interval` public.
- Add getters on `Nonce`, `Report`, `ReportShare`, and `Task`.
- Add conversion functions between `HpkeConfigId` and `u8`.

The `message` module can be split up between the common crate and the server crate. The `Task` struct can likewise be split into one structure with common parameters, and an aggregator-only structure which combines a common task struct with verification parameters, private keys, and symmetric keys.

The `hpke` module currently doesn't expose any useful APIs as public. We will need to either expose open/seal/additional_data_for, or write new public methods, one that produces a `Report` given sharded inputs and other parameters, plus a method that decrypts the payload of a `ReportShare`, and similar for aggregate shares.

**Comment by divergentdave** [comment]
Here's what's left to split out a client crate.

* Add accessor methods to `Task`.
* Split the Task struct into a common type (with the TaskId, aggregator endpoints, and VDAF with its parameters) and an aggregator-only type.
* Make changes to our `Vdaf` enum such that we can move or split it. We will want some type in the common crate that describes VDAFs and their parameters, but the current definition inside `janus_server` uses conditional compilation to introduce testing-only variants. The two apparent solutions are to expose these "fake VDAF" variants publicly in the common crate, but only when a new Cargo feature is enabled, or to define one enum in the common crate, and a wrapping enum in the `janus_server` crate with the same `[cfg(test)]` conditional compilation, then fix up Serialize/Deserialize implementations of the wrapping enum with conversions or serde boilerplate.
* Create the janus_client crate, and move the contents of `client.rs` into it.

**Comment by divergentdave** [comment]
Given how little is shared between client and aggregator views of a task, I'm considering making their `Task` structs entirely independent of each other. In the alternative, I'd want to make the common structure generic, so that `janus_server` could substitute in its own mock-ready `VdafInstance`.
