### ISSUE TITLE
Consider caching collection job results by batch ID & aggregation parameter

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#1802]
As of https://github.com/divviup/janus/pull/1799, if we receive multiple identical collection requests (by batch ID, aggregation parameter) with differing collection job IDs, we will happily service all of them. The aggregation work will be deduplicated, but all collection jobs will independently compute the final aggregate share data.

We could save a bit of work for this case by deduplicating the aggregate share computation, as is done by the Helper when servicing an `AggregateShareReq`. This is likely of somewhat marginal value, as the use-case for sending multiple identical collection requests is marginal (most likely, recovery from some transient failure that caused the original collection job request to be dropped on the ground).

**Comment by inahga** [comment]
We do this now https://github.com/divviup/janus/pull/2957.
