### ISSUE TITLE
Add `created_at` and `updated_at` columns to database tables

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1858]
Frequently, when debugging, we want to understand when some persisted entity was created or updated. For example, if we see that a collection job creation request fails, we want to know when the relevant aggregation jobs were created or updated into the `FINISHED` state.

We should add `created_at` and `updated_at` columns to database tables to that end.

**Comment by branlwyd** [comment]
This likely doesn't need to be said, but our implementation strategy for populating these should be entirely transparent above the datastore layer; they shouldn't be reflected in the models (e.g. `ReportAggregation`), and the various datastore operations (e.g. `put_report_aggregation`, `update_report_aggregation`) should fill in these columns automatically & transparently.

**Comment by tgeoghegan** [comment]
In Slack, @jbr noted we might want to add `updated_by`, as well. Divvi Up's Janus deployments use a distinct postgres user per component (e.g., `aggregator` vs. `aggregation_job_driver`), so that could be useful additional signal, at the risk of growing each row in the database table.
