### ISSUE TITLE
Docs: state that Janus components can be run in parallel

### ISSUE THREAD

**Issue by jonathanherzog** [divviup/janus#1920]
Is it safe to run multiple instances of the Janus containers (`aggregator`, `aggregator-job-driver`, etc) in parallel, all talking to the same database? I have to believe that it is, given the architecture, but need to confirm it and the documentation doesn't say.

**Comment by tgeoghegan** [comment]
Yes, a Janus leader needs four components (`aggregator`, `aggregation_job_driver`, `aggregation_job_creator` and `collection_job_driver`) running concurrently, all on top of the same database. A Janus helper only needs `aggregator`.

We should keep this issue open to improve the documentation, either in one of Janus' READMEs or over in https://github.com/divviup/public-docs.

**Comment by jonathanherzog** [comment]
Great. Thanks for the answer.
