### ISSUE TITLE
Question: key-material from DB or environment variables?

### ISSUE THREAD

**Issue by jonathanherzog** [divviup/janus#1921]
When I look through the example `tasks.yaml' file (https://github.com/divviup/janus/blob/main/docs/samples/tasks.yaml) I see some cryptographic secrets: KPKE private keys, bearer tokens, and VDAF keys. Is it possible to get these secrets from environment variables rather than files? Or out of a KMI? I'd prefer not to write these secrets to non-volatile storage outside of my KMI.

**Comment by branlwyd** [comment]
Janus-level secrets can be provided by environment variable; for example, [`DATASTORE_KEYS`](https://github.com/divviup/janus/blob/main/docs/DEPLOYING.md#datastore-keys) defines the key(s) used to encrypt/decrypt sensitive values from Janus' datastore.

Task-level secrets, such as those found in the tasks.yaml file, are stored in Janus' datastore. We do not currently support receiving these values via environment variable or KMI. However, Janus encrypts these values before storing them; would this meet your needs?

**Comment by branlwyd** [comment]
If you're curious, the datastore encryption is implemented via Crypter: https://github.com/divviup/janus/blob/6d4a164c64f33b4a2fb41e75deec4a4d2c9cffeb/aggregator_core/src/datastore.rs#L4868-L4873

It uses an AAD (AES-128-GCM) that ecnrypts, associating the table/row/column being stored to via the AAD.

**Comment by tgeoghegan** [comment]
I'll add that `tasks.yaml` is meant to be used with `janus_cli` to provision tasks, but that's not what we do in our production deployments. Instead, we use the aggregator API (implemented in the `janus_aggregator_api` crate), which is an extra control plane API that Janus can expose alongside the data plane DAP API. I bring this up to make it clear that you don't _have_ to somehow provide a `tasks.yaml` full of secrets to Janus.

We don't have any mechanism for providing these per-task secrets in environment variables; they are always written to the database.

We currently store bearer tokens but we do plan to start storing token hashes instead (#1509). Of course that only works for the verifier side; a Janus leader would still need to store an unhashed bearer token so that it could authenticate to a Janus helper.

**Comment by jonathanherzog** [comment]
Thanks for the helpful info. I've been trying to consolidate information about the various kinds of cryptographic secrets, and here's what I have so far. Can someone please tell me if I got anything wrong, or if I missed anything?

- HPKE key-pairs:
	- Generation/provisioning: Either provided as part of tasks.yaml to `janus-cli`, or generated inside Janus via aggregator API as per https://github.com/divviup/janus/blob/main/docs/CONFIGURING_GLOBAL_HPKE_KEYS.md
	- Non-volatile storage: database (encrypted with datastore key) and `tasks.yaml` (for those provisioned that way).
- Task-specific vdaf_verify_keys:
	- Generation/provisioning: either provided as part of tasks.yaml to `janus-cli`, or derived from the task ID as part of the taskprov sub-protocol (https://datatracker.ietf.org/doc/html/draft-wang-ppm-dap-taskprov-04#name-deriving-the-task-id)
	- Non-volatile storage: database (encrypted with datastore key), and `tasks.yaml` for tasks provisioned that way
- verifiy_key_init:
	- Generation/provisioning: provided through the Aggregator API as described in https://github.com/divviup/janus/blob/main/docs/CONFIGURING_TASKPROV.md.
	- Non-volatile storage: database, encrypted with datastore key
- Bearer tokens
	- Leader-to-helper authentication (`aggregator_auth_tokens`):
		- For Taskprov:
			- Generation/provisioning: provided through the Aggregator API as described in https://github.com/divviup/janus/blob/main/docs/CONFIGURING_TASKPROV.md.
			- Non-volatile storage: database, encrypted with datastore key
		- For tasks:
			- Generation/provisioning: Either provided as part of tasks.yaml to `janus-cli`, or generated inside Janus via aggregator API
			- Non-volatile storage: database (encrypted with datastore key), and `tasks.yaml` for tasks provisioned that way
	- Collector-to-leader authentication (`collector_auth_tokens`)
		- Generation/provisioning: Either provided as part of tasks.yaml to `janus-cli`, or generated inside Janus via aggregator API
		- Non-volatile storage: database (encrypted with datastore key), and `tasks.yaml` for tasks provisioned that way
- Datastore keys
	- Generation/provisioning:  the `DATASTORE_KEYS` environment variable or `--datastore-keys` command-line argument
	- Non-volatile storage: Never stored to file system or database
- Posgresql password:
	- Generation/provisioning: Command-line argument, environment variable, or in configuration file
	- Non-volatile storage: Never stored to file system or database

**Comment by tgeoghegan** [comment]
The task-specific `vdaf_verify_keys` can also be provided to the Janus aggregator API during task provisioning, for deployments that use neither `tasks.yaml` nor taskprov.

**Comment by jonathanherzog** [comment]
Got it. Thanks.
