### ISSUE TITLE
Cap the number of retries that a database tx can undergo

### ISSUE THREAD

**Issue by inahga** [divviup/janus#2124]
As discussed in slack https://isrg.slack.com/archives/C0167LT4C73/p1697139388022519.

It is possible for a client to attempt to insert a task whose ID collides with an expired task. When this happens, an infinite loop of retries is triggered.

The trigger is illustrated with this example client https://github.com/divviup/janus/commit/538a244744c3b5ccec3b2a72cbc5afdd8b0dc860#diff-9cbf3f0a31c9bbe4a567f128a2f4fd96fb100fe794131ff92e42400779ba85f1.

Besides needing to fix this bug, we also identified several Janus improvements that help with troubleshooting and limiting the impact of this class of bug:
- [ ] Cap the number of retries that a tx can undergo, 
- [x] and add associated logging and metrics.
- [x] ~Add exponential backoff to retries~ we don't think this is necessary at this time as retries should be very rare, but it's something we can keep in mind.
- [x] ~https://github.com/divviup/janus/issues/2120, this bug was originally discovered because the Google crawler was scraping a Janus subscriber's site. It has deterministic RNG and thus was sending the same report ID on every site crawl~. Not going to implement this in janus, this is a front-end LB concern.
- [x] Add the ability to change log level at runtime https://docs.rs/tracing-subscriber/latest/tracing_subscriber/reload/index.html

**Comment by tgeoghegan** [comment]
It seems like the only thing left to do in Janus is to cap the retries on DB transactions. Retitling to make it clear that we have addressed the bug that caused the infinite retries.
