### ISSUE TITLE
SQL schema: reconsider type of `report_aggregations.error_code`.

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#22]
Recording changes to the storage schema I think we will need.

- [x] enum `VDAF_IDENTIFIER` needs more entries to align with VDAFs instantiated in https://datatracker.ietf.org/doc/draft-patton-cfrg-vdaf/
```
-- Identifies a particular VDAF.
CREATE TYPE VDAF_IDENTIFIER AS ENUM(
    'PRIO3AES128COUNT',
    'PRIO3AES128SUM',
    'PRIO3AES128HISTOGRAM',
    'POPLAR1'
);
```
- [x] VDAF verification parameters are secret (https://datatracker.ietf.org/doc/draft-patton-cfrg-vdaf/ section 4.1) and also have to be rotated at some interval. Therefore `vdaf_verify_param` should not be in table `tasks`.
- [x] `tasks.min_batch_duration` is an `INTERVAL`, which is awkward and can be surprising ([discussion](https://github.com/divviup/janus/pull/33#discussion_r833787897)). Consider storing that as a BIGINT (better matches how we will use it in code anyway).

**Comment by divergentdave** [comment]
`report_aggregations.error_code` could stand to be a nullable `smallint` or nullable `ENUM`, rather than a nullable `bigint`.

**Comment by divergentdave** [comment]
I think we should add a `UNIQUE(task_id)` constraint on the tasks table.

**Comment by tgeoghegan** [comment]
I think we should lump this in with the other [draft-ietf-ppm-dap-02 changes](https://github.com/divviup/janus/milestone/1) since this means changing the DB schema, which is a breaking change until we have a DB migrations story.
