### ISSUE TITLE
Verify that janus implements draft-ietf-ppm-dap-01

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#221]
Once draft-ietf-ppm-dap-01 is published, we should make sure that `janus_server` implements it. I believe this mostly consists of making sure we have the right HTTP problem document type strings and other naming things. We also should fix references in comments to draft sections, since those mostly refer to the sections from the interop branch of the DAP draft.

**Comment by BranLwyd** [comment]
- [ ] We don't currently reject reports that fall into batch intervals that have already been collected.

**Comment by tgeoghegan** [comment]
We've been doing interop testing with other draft-01 implementations for a little bit and we're not aware of other specific issues related to draft-01, so I'm going to close this.
