### ISSUE TITLE
Review `Debug`, `Display` impls on structs exported from Janus API crates

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#2225]
We derive `Debug` on `janus_client::Client`, which I endorse, but I suspect we should do that via `derivative` to trim some large fields. Also, we could provide a `Display` implementation. We should audit all the structs we export from `janus_client`, `janus_collector` and `janus_messages` and see that they're up to some unarticulated standard of having "nice" `Debug+Display` implementations.

**Comment by branlwyd** [comment]
+1 to better `Debug` implementations.

What do you imagine the `Display` implementation for these would look like? The only(?) [guidance](https://doc.rust-lang.org/std/fmt/trait.Display.html) Rust provides on Display vs Debug is "Display is similar to Debug, but Display is for user-facing output". But I'm not sure most of these structs have sensible user-facing formats -- e.g. I can't imagine what one would expect a DAP client to format as in the terminal. At most, these structures might get logged, which (I think?) would typically want the Debug implementation.

**Comment by tgeoghegan** [comment]
That's true; given that using the `Debug` impl is just a matter of `:?`, then we could skip providing `Display`s as there tends to be a stronger expectation of stability with those.

**Comment by branlwyd** [comment]
This is effectively done. We should be careful with future changes not to introduce new large or sensitive fields into our `Debug`/`Display` outputs.
