### ISSUE TITLE
messages: Replace `type Err = Box<dyn Debug>` with an actual Error type

### ISSUE THREAD

**Issue by inahga** [divviup/janus#2236]
Breaking change: Some of our FromStr implementations have the associated `Err` type `Box<dyn Debug>`. This can make it difficult to interop these structs with other crates, such as clap, which expect `T` to be something more like `<T as FromStr>::Err: Into<std::error::Error>`.

We can change the Err type to be a `thiserror` derived type.

This change would let us get rid of the custom `TypedValueParser`s in collect.rs, and generally make it easier to build CLI tools that construct messages.

**Comment by tgeoghegan** [comment]
We're currently in the window where we can take breaking changes for Janus 0.7, so we should do this soon.
