### ISSUE TITLE
`batch_aggregations.batch_interval`, `batch_aggregations.client_timestamp_interval` are unused.

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#2251]
The fields `batch_aggregations.batch_interval`, `batch_aggregations.client_timestamp_interval` are unused, and can be removed with migration.

(I didn't do the legwork to track down how we arrived at computing & storing these vestigial fields, but I suspect they were once used for GC, but no longer are.)

**Comment by branlwyd** [comment]
Additionally, we only use the maximum of `aggregation_jobs.client_timestamp_interval`, `batches.batch_interval`, & `batches.client_timestamp_interval`. We could achieve a very marginal space savings by storing only the maximum timestamp rather than the interval; but this would require a migration, so it is likely not worth the effort outside of a major-version break.

If/when we drop support for the time-interval query type, we could switch to storing only the minimal timestamp rather than the entire interval for the `collection_jobs.batch_interval` & `aggregate_share_jobs.batch_interval` fields.

**Comment by tgeoghegan** [comment]
We're currently in a breaking-changes window for Janus 0.7, so we should do this soon.
