### ISSUE TITLE
Upgrade http ecosystem crates

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2295]
Once reqwest and http-api-problem have both released new versions that use types from http 1.0.0, we should update all three crates at once.

**Comment by divergentdave** [comment]
hyper-rustls 0.26.0 was just released, which supports http ^1 and hyper ^1. The next pieces are an h3 release and updates to reqwest itself.

**Comment by tgeoghegan** [comment]
We should upgrade `retry-after` from 0.3.1 to 0.4.0 (or whatever's current) once we can move the whole world to `http 1.0` (see #2830).
