### ISSUE TITLE
Support accepting connections to the aggregator over TLS

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#232]
Currently, our HTTP listener can only listen for HTTP (rather than HTTPS) connections. We should support accepting connections over TLS.

**Comment by BranLwyd** [comment]
(this may also be handled by putting a load balancer or other piece of TLS-terminating infrastructure in front of our aggregators; that's an alternate path to closing this bug)

**Comment by cjpatton** [comment]
For interop testing it will be useful to have HTTP only.

**Comment by branlwyd** [comment]
I'm closing this bug: we already terminate HTTPS in our "real" (e.g. cloud-based) deployments outside of Janus, and have no need to use TLS at all for more ephemeral deployments (unit tests, integration tests, one-off manual tests, etc).

**Comment by branlwyd** [comment]
(assigning David as IIRC he did the operational work to enable terminating TLS in our cloud-deployed instances)
