### ISSUE TITLE
Consider aborting aggregation jobs entirely on certain errors from helper

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#235]
When in the leader position, the aggregation job driver will currently retry (until normal too-many-retries logic causes us to stop) on _any_ HTTP failure. Certain HTTP error codes and/or DAP error codes should probably cause us to abandon the aggregation job immediately. We may also want to give up if the helper responds with an unknown/unexpected content type.

**Comment by tgeoghegan** [comment]
See also #1180 which has a lot of discussion around avoiding scheduling aggregation jobs that can't succeed. We need to articulate state machines for reports, aggregation jobs, collections and aggregate shares, see where they intersect and then implement that coherently, which might also feed back into DAP itself.
