### ISSUE TITLE
get_task_metrics() is expensive and must be destroyed

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2360]
Here's a recently executed query plan:

![image](https://github.com/divviup/janus/assets/181772/04cfe214-7a77-4fb1-b2c8-302ef77e89a3)

**Comment by inahga** [comment]
From discussion [out of band](https://isrg.slack.com/archives/C0167LT4C73/p1706030221975669), we probably will want to delete this function as-it-is. While it has information that might be useful, it is slow for large tasks even with index scans, there may be better ways to get the same information, and it isn't currently useful for billing purposes.

**Comment by tgeoghegan** [comment]
Elsewhere we have work underway (#2293, #2508, #2537, #2553, #2513) to introduce a superior task metrics solution. So I think this issue only tracks deleting the old solution once the new one is deployed.
