### ISSUE TITLE
Leader: Batch GC can cause an aggregation job to become unwritable.

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#2464]
In the presence of GC, an aggregation job can become unwritable if one of the relevant underlying batches is garbage collected. Specifically, the error occurs due to an underflow in `outstanding_aggregation_jobs`.

An example flow reproducing this issue:
1) Aggregation job is created, including a report that references some batch `B`. `B`'s `outstanding_aggregation_jobs` counter is incremented at this point.
2) `B` is GC'ed.
3) The aggregation job is written, for example because of an attempt to step it. The `aggregation_job_writer.rs` logic will not read `B`, will create a new batch with `outstanding_job_count` of 0, and will decrement that count, leading to an underflow to `u64::MAX`.
4) Upon attempting to write the batch, we will attempt to convert `u64::MAX` to an `i64`, which leads to an integer conversion error.

(h/t @inahga for analysis)

**Comment by branlwyd** [comment]
The fix approach discussed so far: augment `get_batch` to return whether the batch is GC'ed, and use that to ignore batch writes to GC'ed batches.

This is tricky: we can determine this for time-interval (since the GC condition is based on the batch interval for the batch, which is used as the primary identifier to the batch); but for fixed-size, the GC condition is based on the maximum client timestamp contained in the batch, which we need to have the batch around to determine.

However, I think we don't need to care for fixed-size: in the fixed-size query type, the GC condition for both batches & aggregation jobs is based on the maximum of the included client timestamp interval, and all reports in an aggregation job are attached to the same batch. This implies that all aggregation jobs in a batch will be GC'ed at or before the batch is GC'ed.

So: I think this bug does not exist in the fixed-size query type, and we can use the discussed approach but only for the time-interval query type. I'm not totally happy with this because it's yet another time-interval-only hack; we're piling more query-type-specific complexity on.

**Comment by branlwyd** [comment]
There may be a similar issue in the Helper codepath (`handle_aggregate_init_generic`, `handle_aggregate_continue_generic` in `aggregator.rs`), which should be investigated; but it's likely less severe since we do not count outstanding aggregation jobs in the Helper.

**Comment by tgeoghegan** [comment]
I'm comfortable with the fix in #2467, noting that it's not perfect. IIUC, the problem here is that we might GC a batch, but leave some dangling references to it in aggregation jobs. Would a more thorough fix here be to have the GC process update aggregation jobs to remove expired batches from them? Or maybe we could just delete aggregation jobs that include any GCed batch, and then any non-expired reports that were in that aggregation job would get rescheduled subsequently by the aggregation job creator?

**Comment by branlwyd** [comment]
Other than the points raised by David above, I think we should also try to keep the different types of objects (report state / aggregation state / collection state) as independent as possible, for performance reasons.

**Comment by tgeoghegan** [comment]
Fair enough -- I perhaps shouldn't have waded into specifics since I haven't spent as much time with this issue as others have lately, but what I'm really getting at is: do we consider #2467 good enough, or do we want to consider further changes that would let us remove what we deem to be a hack?

**Comment by branlwyd** [comment]
My thoughts on less-hacky solutions, from least- to most-impactful:

* We could introduce an equivalent check as a method on `AccumulableQueryType`, something like `is_batch_garbage_collected` (returning `Option<bool>` indicating yes, no, or unknown); or `should_write_batch` (returning `bool`). This is effectively the same logic as in the current solution, just factored to be a little more palatable.
* For time-interval, somehow grouping reports into aggregation jobs such that all reports for a given aggregation job are in the same batch. This would guarantee that all aggregation jobs would be GC'ed before the relevant batch. But it might leave stragglers in each batch that we'd need to account for somehow -- right now we won't allow collection if there are any existing unaggregated reports. (We might decide to generate an undersized aggregation job for a given batch once we are sure no more reports can arrive for that batch?)
* An unknown/unscoped modification to time-interval GC such that batches can't be GC'ed until all of the relevant aggregation jobs are GC'ed. (similar to what you mention above) I can't think of an approach here that wouldn't have a pretty negative impact on GC/overall-system performance, due to the additional dependence between different entities when being evaluated for GC.
* Drop time-interval support. All of our GC bugs are time-interval only, so far; this is likely due to us having more experience deploying time-interval, but also fixed-size permits a more "regular" GC where different entities' lifecycles can be bounded within one another, so it's plausible that fixed-size GC is also just easier to get right.

I'm going to investigate at least the first suggestion once we've seen that the "hack" solution solves the issue.
