### ISSUE TITLE
`janus_server`: set up Warp rejection handlers to send correct responses to HTTP clients in error cases

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#25]
We should use `warp::filter::recover` to do something with `Rejection`s from filters to massage them into responses with appropriate HTTP status codes and bodies.

See comment on PR #23: https://github.com/abetterinternet/janus/pull/23#issuecomment-1069552558

**Comment by divergentdave** [comment]
To reiterate a [comment on #23](https://github.com/abetterinternet/janus/pull/23#discussion_r829381568), I think we should not pass `crate::Error` through rejection and recovery, as it is non-idiomatic to handle application errors with this mechanism. Instead, we should make each filter with aggregator business logic return `Result<impl Reply, Error>`, and then chain a filter after our router that will take that result as an input, turn errors into problem documents, and return `impl Reply`.
