### ISSUE TITLE
Breaking changes for Janus 0.7.0

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#2588]
We still have the opportunity to make breaking changes to Janus 0.7.0 as we have only released prerelease versions of it so far. Let's break public Rust API, database schema, emitted binaries!

- [x] <s>https://github.com/divviup/janus/issues/2312</s>
- [x] https://github.com/divviup/janus/issues/2236
- [x] https://github.com/divviup/janus/issues/2251
- [x] https://github.com/divviup/janus/issues/2329
- [x] <s>https://github.com/divviup/janus/issues/2463</s>
- [x] https://github.com/divviup/janus/issues/2608

**Comment by inahga** [comment]
I landed a few breaking changes. Here's some summaries for the release notes:

- `DivviUpHpkeConfig` has been removed. Use `PrivateCollectorCredential` instead.
- `PrivateCollectorCredential::hpke_keypair()` has been made infallible. `PrivateCollectorCredential::hpke_keypair_infallible()` has been removed, replace it with `PrivateCollectorCredential::hpke_keypair()`.
- The `token` field of `PrivateCollectorCredential` has been made non-optional. If your credentials are missing this field, you should regenerate the credentials with a newer version of `divviup-cli`. Alternatively, you can edit the credential manually to supply the `token` field.
- The aggregator configuration field `max_job_discovery_delay_secs` used by job drivers has been fully removed. Replace it with `job_discovery_interval_secs`.

**Comment by divergentdave** [comment]
Now would be a good opportunity to clean up Prio3CountVec support, since Prio3SumVec has been properly specified for a while.

**Comment by tgeoghegan** [comment]
We're keen to release Janus 0.7.0, and have agreed to punt #2463 to a later breaking period. #2312 can be done in a backward compatible way, so it's not a breaking change and can be taken at any time during the 0.7.0 release cycle.

**Comment by tgeoghegan** [comment]
We released [Janus 0.7.0](https://github.com/divviup/janus/releases/tag/0.7.0), so we're done here.
