### ISSUE TITLE
Halt request processing when the request is cancelled

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#2604]
We should investigate whether Janus cancels processing of requests that are cancelled (e.g. because the request timed out or the client otherwise left).

If not, we should ensure that request processing is halted when the request is cancelled. Other than saving on wasted processing, this would also mitigate (but not solve) issues where the Leader & Helper can become out of sync on which reports are included in an aggregation job.

**Comment by branlwyd** [comment]
@jbr can you comment on Trillium's behavior w.r.t. cancelled requests -- will the handler be cancelled or continue processing?

**Comment by jbr** [comment]
The handler will run to completion if the client disconnects between sending a fully-formed header section and the handler beginning. I'll think about ways to opt into checking for liveness, but I think we're going to be hampered by the constraint that there is no way to tell if a tcp connection has closed without reading or writing a byte, and the http spec doesn't provide for a byte that is safe to send between request receipt and response transmission.

**Comment by jbr** [comment]
One option would be to hold a transaction open until the request has completed sending and roll back on failure.

**Comment by branlwyd** [comment]
[Trillium 0.2.14](https://github.com/trillium-rs/trillium/releases/tag/trillium-v0.2.14) has [`Conn:cancel_on_disconnect`](https://docs.rs/trillium/latest/trillium/struct.Conn.html#method.cancel_on_disconnect) which will likely help. We should adopt usage soon.

**Comment by jbr** [comment]
@branlwyd Additionally, [trillium-api@0.2.0-rc.9 contains a CancelOnDisconnect handler for handlers that don't need &mut Conn](https://docs.rs/trillium-api/0.2.0-rc.9/trillium_api/struct.CancelOnDisconnect.html)

**Comment by branlwyd** [comment]
@jbr Thanks for taking this on. One thing I forgot to mention while discussing: this should be backported to the `release/0.6` branch as well as being implemented on `main`.

**Comment by inahga** [comment]
We're doing this now! :tada:
