### ISSUE TITLE
Helper aggregation: do not perform VDAF computations, writes for repeated requests

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#2606]
Currently, on a repeated request, the Helper will recompute the VDAF steps etc before checking whether the request is a repeated, idempotent request. We should move this check to happen before the computation; this will likely drastically reduce the cost of repeated requests.

The reason we do not do this currently is that we don't open a DB transaction until after all of the VDAF computation is complete. We should investigate if we can perform the necessary reads piggybacking off of some other DB transaction. (I think there may not be one to piggyback off of, however.)

**Comment by branlwyd** [comment]
Unassigning, I need to prioritize cost-optimization work for now. I don't think we have evidence this will have a large positive effect, and we might have to introduce a new DB transaction to implement it, so it's plausible it might have a negative effect on the DB as well.

**Comment by inahga** [comment]
We do this now. https://github.com/divviup/janus/pull/3135.
