### ISSUE TITLE
Simplify interval_has_unaggregated_reports()

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2646]
The query in `interval_has_unaggregated_reports()` uses a range containment operator on `client_reports.client_timestamp`. From inspection of query plans, this cannot be lifted to index conditions, and instead ends up being executed as a filter. This can become inefficient if there are many unaggregated reports. We should turn this `<@` into a `>=` and `<`, which can be satisfied with index conditions. We should also check for other unusual operators used on columns that only have btree indices.

**Comment by tgeoghegan** [comment]
David fixed the most egregious case of this, but we should still audit other queries that act on intervals and amend them.

**Comment by branlwyd** [comment]
I surveyed additional uses of containment operators: they are on either `collection_jobs.batch_interval` or `aggregate_share_jobs.batch_interval`, both of which have a GiST index. I think we are OK here, and should create a new issue if we discover other query inefficiencies.
