### ISSUE TITLE
"cannot call init when there are already clones of an Arc<Handler>"

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2655]
We're seeing async tasks panic with "cannot call init when there are already clones of an Arc<Handler>" intermittently. This panic is inside trillium, at `trillium-0.2.15/src/handler.rs:218:14`. The panic happens repeatedly, but is intermixed with log messages from requests handled successfully. It's possible this is interrupting incoming requests, and causing liveness checks to fail.

**Comment by divergentdave** [comment]
@jbr points out that this could be from where we pass around `Arc<aggregator::Error>`, and later use it as a handler. I think these `Arc`s only get cloned in the case where a batched upload transaction fails, and the resulting error gets passed over channels to all waiting request handler tasks. We could either move our `Handler` implementation from `Error` to `Arc<Error>`, or this could possibly be addressed at the Trillium level.

**Comment by jbr** [comment]
Downgraded from a panic to a warning for now in [trillium@0.2.16](https://github.com/trillium-rs/trillium/releases/tag/trillium-v0.2.16), but I recommend moving the Arc into the variant(s) that aren't Clone instead of Arcing the whole error — that also would likely decrease the size of the Error type

**Comment by branlwyd** [comment]
If we make a change to `Error` in Janus, I think we should follow the `Error(Arc<InnerError>)` pattern instead of `Arc`'ing only the variants that aren't `Clone`.
