### ISSUE TITLE
Change when we allow below-minimum aggregation jobs

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#2733]
Make it a new configuration parameter instead of using time_precision

**Comment by tgeoghegan** [comment]
I don't believe I understand this enough to write it up coherently. @divergentdave I expanded this from a Slack comment you made. Could you flesh this out a bit?

**Comment by divergentdave** [comment]
The documentation on `min_aggregation_job_size` says "For time-interval tasks, applies to the "current" batch only; historical batches will create aggregation jobs of any size, on the theory that almost all reports will have been received for these batches already." However, looking at the aggregation job creator, I don't think this is any more the case. The aggregation job creator currently sorts by time/batch, takes reports from one or more consecutive batches until it has at least `min_aggregation_job_size` reports, and creates jobs with at most `max_aggregation_job_size` reports. Thus, the current time no longer is a factor in aggregation job size, and the aggregation job creator always obeys `min_aggregation_job_size` for time interval tasks. (we just need to raise `min_aggregation_job_size` higher than one) Thus, this idea is moot.
