### ISSUE TITLE
Handle repeated collection jobs in one database transaction

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2751]
Currently collection jobs for new and repeated batches share some code paths. As a result, we write back batch aggregations to the database unchanged, and split work across two database transactions, though no HTTP request happens between the two. This could be rewritten to reduce writes and handle repeated requests in only one transaction, but we probably don't get that many repeated collection requests.

**Comment by branlwyd** [comment]
This performance optimization was implemented as part of #2782 & then improved in #2957 -- now, repeated collection jobs are handled in one DB transaction, without writing anything back except the completed collection job.
