### ISSUE TITLE
Scalability/performance improvements

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#2868]
This is an umbrella tracking issue for Janus scalability & performance-related changes. We have a number of integrations with a variety of different scaling needs; this issue will track both work done to improve scalability as well as targets for scalability improvements.

Useful axes likely include:
* Required per-task report processing rate vs total report rate over all tasks
* Aggregator role (Leader vs Helper)
* VDAF in use
* Query type in use

Recent performance work includes:
* https://github.com/divviup/janus/pull/2782
* https://github.com/divviup/janus/pull/2857 (generalizing the prior https://github.com/divviup/janus/pull/2560 & https://github.com/divviup/janus/pull/2807)
* https://github.com/divviup/janus/pull/2818 (fixes an important class of DB-retry bugs which had significant performance impact)

**Comment by inahga** [comment]
We've accomplished all outstanding performance work outlined in this issue. As more ideas come up, we'll open new issues.
