### ISSUE TITLE
Rationalize use of rayon in Prio3 VDAFs using ParallelSum

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#2956]
We are inconsistent about whether we use the "multithreaded" variant of VDAFs. When constructing `VdafOps` in the aggregator, we use `Prio3::new_sum_vec_multithreaded()` and `Prio3::new_fixedpoint_boundedl2_vec_sum_multithreaded()`, but don't use multithreading for `Prio3SumVecField64MultiproofHmacSha256Aes128` or `Prio3Histogram`. The situation is similar in `vdaf_dispatch!`. We should either use this in all situations, or none of them. `ParallelSumMultithreaded` only behaves differently in its `call_poly()` method, which is only used when proving, not when querying. (technically, it would be possible to parallelize `ParallelSumMultithreaded::call()`, but it wouldn't be worth it, because evaluating the circuit on the query point `r` takes far less time than the rest of the query algorithm, i.e. interpolating wire polynomials and evaluating them) Thus, we could standardize on using the non-multithreaded versions in the aggregator, as a cleanup.

**Comment by cjpatton** [comment]
Question: can you even use rayon within async code?

I'm OK with dropping the rayan-acclerated aggregator bits. Daphne (in particular Cloudflare's service that operations Daphne) will not use this: for us it's sufficient to to parallelize across reports while handling an aggregation job.

There may still be benefit for the client to use rayon, since all the work it needs to do pertains to a single report.

**Comment by divergentdave** [comment]
With Tokio as an async runtime, doing CPU-intensive computations inside futures/async functions is frowned upon, as it can have bad impacts on tail latencies. (see #2955) [Tokio's recommendation](https://docs.rs/tokio/latest/tokio/#cpu-bound-tasks-and-blocking-code) is to spawn work onto rayon's threadpool, and then use Tokio oneshot channels to send the result from the threadpool back to the asynchronous task.

Note that since aggregators don't use `ParallelSum::call_poly()`, their operation isn't actually accelerated by rayon (and there isn't much that's parallelizable). I think we are also mostly settled on coarser parallelization in Janus.

**Comment by branlwyd** [comment]
I would vote for parallelizing over reports, rather than using parallelized VDAFs. That is, I agree with the thrust of this issue, I think.
