### ISSUE TITLE
Helper: More than two aggregation jobs containing the same report cause 500 error.

### ISSUE THREAD

**Issue by inahga** [divviup/janus#3142]
If two aggregation jobs come in that contain the same report, one will prepare the report successfully, and the second will reject the report, as expected.

If a third comes in, the result is a 500 error. The problem is in the function `check_other_report_aggregation_exists()` which does this query in a `query_opt()` call.
```
                "-- check_other_report_aggregation_exists()
SELECT 1 FROM report_aggregations
JOIN aggregation_jobs ON aggregation_jobs.id = report_aggregations.aggregation_job_id
WHERE report_aggregations.task_id = $1
  AND aggregation_jobs.task_id = $1
  AND report_aggregations.client_report_id = $2
  AND aggregation_jobs.aggregation_param = $3
  AND aggregation_jobs.aggregation_job_id != $4
  AND UPPER(aggregation_jobs.client_timestamp_interval) >= $5",
```
If there are multiple report aggregations, this query returns more than 1 row, which returns an error from `query_opt()` which propagates up to a 500 error.

**Comment by branlwyd** [comment]
The OP is true; but more than that, if the aggregation jobs containing the replayed report arrived concurrently, Janus would have aggregated both. This is potentially a privacy bug. The fix for both of these issues is tracked in #3143.
