### ISSUE TITLE
Add janus version to API

### ISSUE THREAD

**Issue by simon-friedberger** [divviup/janus#3332]
It's useful for debugging to be able to check which version of Janus an aggregator is running. The / route for the API already returns something like:
```
{
  "protocol": "DAP-09",
  "dap_url": "...",
  "role": "Either",
  "vdafs": [
    "Prio3Count",
    "Prio3Sum",
    "Prio3Histogram",
    "Prio3SumVec"
  ],
  "query_types": [
    "TimeInterval",
    "FixedSize"
  ],
  "features": [
    "TokenHash",
    "UploadMetrics",
    "TimeBucketedFixedSize"
  ]
}
```
This could include a `"version": 0.7.27`. And it would of course be extra nice if the leader would check the version of the helper and make sure that it's compatible with the operations it is trying to perform. Although, maybe that's what "features" is for.

**Comment by divergentdave** [comment]
Yes, the features list is used to ensure compatibility with specific operations. This sounds like a good idea for diagnostic purposes. (The version number is already exposed via Prometheus metrics, FWIW)
