### ISSUE TITLE
Speed up database used in tests

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#3359]
I've seen that starting up the database process takes around four to five seconds locally, while setting up a new database and applying the schema takes a bit under one second. Cutting these times down could be a nice improvement to our test throughput.

Since the ephemeral databases used in tests don't need to be durable, we could LD_PRELOAD libeatmydata inside the database container, in order to make fsyncs no-ops. We'd need a Dockerfile that inherits from the postgres image, installs `libeatmydata-131-r1`, and sets the LD_PRELOAD environment variable.

Alternately, we could mount a tmpfs volume and point the image at it with the `PGDATA` environment variable. This would speed up all disk operations significantly, so long as we don't run out of memory.

**Comment by inahga** [comment]
TIL https://github.com/stewartsmith/libeatmydata.
