### ISSUE TITLE
Error type returned from /upload upon receiving a duplicate report

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#34]
I think we may need to revisit the error type we return when multiple reports are uploaded with the same nonce. Currently, we return `Error::StaleReport`, whic will become urn:ietf:params:ppm:error:staleReport. The spec says this type should indicate to the client that the "report could not be processed because it arrived too late", i.e. the nonce timestamp "falls in a batch interval for which it has received a collect request from the collector".

As we had discussed during a sync meeting, the spec is liberal in its requirements on the aggregator's response to `/upload` in the interest of not imposing operational burdens. In particular, there's no requirement to identify duplicate reports during the upload process, only during aggregation. One could imagine a distributed aggregator with eventually-consistent report storage, which may not be able to detect a report being uploaded twice to different servers around the same time.

Here are three alternatives to the "stale report" error we're currently returning:

1. Return 200 OK and silently drop the report. This would be allowed, but perhaps not the most ergonomic.
2. Define our own error type, perhaps with a `https://divviup.org/...` URI as the type, and use it in a problem details document.
3. Propose an error type in the PPM namespace, along with text saying that aggregators MAY return this error during upload in the event of a duplicate report.

(For the purposes of the error details PR, I'll keep using staleReport for duplicate reports for now)

Long-term, we may want to consider removing the unique constraint on report task IDs and nonces, checking for duplicate reports during `/upload` with only Read Committed isolation, and then explicitly checking for duplicate nonces as we construct aggregation sub-jobs. This would get predicate locks out of our hot write path, at the expense of the complexity working without the uniqueness constraint.

**Comment by tgeoghegan** [comment]
I submitted https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/333 to define a proper error code in DAP for this scenario.
