### ISSUE TITLE
Rename metrics

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#342]
The Prometheus documentation [recommends that](https://prometheus.io/docs/practices/naming/) metric names "should have a (single-word) application prefix relevant to the domain the metric belongs to." Furthermore, we should avoid using "aggregator" as the metric prefix because this is used internally to Kubernetes, for metrics related to the API aggregation layer in `kube-apiserver`.

Here's a list of the metrics we currently define.

- `aggregator_database_transactions_total`
- `aggregator_response_time_{bucket, count, sum}`
- `job_acquire_time_{bucket, count, sum}`
- `job_cancellations`
- `job_creation_time_{bucket, count, sum}`
- `job_step_time_{bucket, count, sum}`
- `step_failures`
- `task_update_time_{bucket, count, sum}`
- `upload_decrypt_failures`

**Comment by divergentdave** [comment]
How about the following new names? They mostly just add `janus_`, but I shortened the database metric name for length's sake.

* `janus_database_transactions_total`, "Count of database transactions run, with their status."
* `janus_aggregator_response_time`, "Elapsed time handling incoming requests, by endpoint & status."
* `janus_job_acquire_time`, "Time spent acquiring jobs."
* `janus_job_cancellations`, "Count of cancelled aggregation jobs" or "Count of cancelled collect jobs" (we should unify these descriptions as well)
* `janus_job_creation_time`, "Time spent creating aggregation jobs."
* `janus_job_step_time`, "Time spent stepping jobs."
* `janus_step_failures`, "Failures while stepping aggregation jobs; these failures are related to individual client reports rather than entire aggregation jobs."
* `janus_task_update_time`, "Time spent updating tasks."
* `janus_upload_decrypt_failures`, "Number of decryption failures in the /upload endpoint."

**Comment by BranLwyd** [comment]
Those names LGTM 👍🏻.
