### ISSUE TITLE
DAP compliance: handle HTTP DELETE requests to collect job URIs

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#344]
According to [DAP-01 section 4.4.1](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-01.html#name-collection-initialization), the leader "`MUST` retain a collect job's results until the collector sends an HTTP DELETE request to the collect job URI".

We currently don't support the `DELETE` verb at all. We should support deleting results when we receive a `DELETE` request.

**Comment by tgeoghegan** [comment]
We should make sure we are in line with the new text in draft-02: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/292

**Comment by tgeoghegan** [comment]
This is implemented in PRs #576, #579, #580, #581. Collect jobs now get marked deleted persistently in the database. However I haven't actually implemented the deletion of any data related to a collect job (tracked in #313). Doing that isn't actually required for DAP-02 compliance (nobody outside of Janus can tell that we have or have not deleted any data), and I think we have some open design questions around how we would approach GC. The obvious thing to do is to immediately delete all data associated with a collect job upon its deletion, but there's no reason to do that work synchronously while `janus_aggregator` handles a request, or even to do it in `janus_aggregator` at all. We might build a whole new component that runs as a cronjob and scans the datastore looking for stale data to garbage collect.
