### ISSUE TITLE
Collect job URI: include task ID & consider normalizing collect job ID

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#347]
DAP leaves the collect job URI scheme unspecified, and therefore up to the implementation. Janus' current URI scheme is `/collect_jobs/{collect_job_id}` where `collect_job_id` is a UUID.

We should change this in a few ways:
 * We should include the task ID in the collect job URI, perhaps with a scheme like `/tasks/{task_id}/collect_jobs/{collect_job_id}`. This would allow us to look up the related task without needing to do a collect-job-ID lookup first, dropping an index hit & I believe an index. (I believe this is the only place we have to look up a collect job by collect job ID only.)
 * We should consider changing the serialization of collect job IDs from UUID to an unpadded base64url encoding of an opaque randomly-generated value. This new encoding scheme would match all other opaque identifiers used in Janus.

**Comment by BranLwyd** [comment]
(another upside of including the task ID in the collect job URI is that task-by-ID lookups are cached, while task-by-collect-job-ID lookups are not & it would not be easy to do so. we'd change the common case from "always do a DB transaction to look up the related task" to "almost never do a DB transaction to look up the related task")

**Comment by BranLwyd** [comment]
The suggested change to the collect job URI will almost certainly dovetail nicely with the upcoming change to DAP to make the HTTP API more resource-oriented, tracked in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/278.

**Comment by tgeoghegan** [comment]
Besides consistency, encoding the collect job ID in unpadded base64url should be more compact than a whole UUID (the `-`s are wasted bytes). I also like surfacing more information in the URI. Besides saving us the DB TXNs (which I think will let us clean up some heinously complicated SQL I wrote), it also allows us do some load balancing based on task ID before traffic ever gets to a Janus pod.

**Comment by divergentdave** [comment]
This is moot following DAP draft-04.
