### ISSUE TITLE
Read-only database transactions

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#359]
We could mark some of our transactions as read-only up front, to enable certain optimizations in the database. The `README-SSI` file from the Postgres source tree says:

> Performance under this SSI implementation will be significantly
> improved if transactions which don't modify permanent tables are
> declared to be READ ONLY before they begin reading data.

I did a quick survey of our transactions, and currently we only have six transactions that would be eligible. Thus, this might not be that much of a win. The transactions are in:

- `Aggregator::handle_collect_job()`
- `Aggregator::task_aggregator_for()`
- `VdafOps::handle_collect_job_generic()`
- `CollectJobDriver::step_collect_job_generic()` (first transaction)
- `AggregationJobCreator::run()`
- `AggregationJobDriver::step_aggregation_job_generic()`

**Comment by tgeoghegan** [comment]
This is a good idea nonetheless. If a query is tagged READ ONLY but it contains an UPDATE or DELETE or some kind of mutation, does that cause Postgres to raise an error at runtime? It'd be neat to construct the interfaces to `janus::datastore::Datastore` such that only READ ONLY queries are possible unless you opt into mutation somehow, to help guard against accidentally having written a query that was meant to be readonly but which mutates data.

**Comment by divergentdave** [comment]
Yeah, I think the straightforward way to do this would be to have separate struct types for read only transactions and normal transactions, move all the getters to provided methods on a new trait implemented for both structs, and move all the update methods to the normal transaction type.

**Comment by divergentdave** [comment]
I'm going to close this, since our workload is predominantly read-write transactions.
