### ISSUE TITLE
Kubernetes compatible liveness/startup/readiness/health endpoint

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#36]
Aggregators should perform health checks at startup and report on an HTTP endpoint that can be used by (among other things) Kubernetes to determine if a running container is healthy.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by tgeoghegan** [comment]
#35 is one such check.

**Comment by divergentdave** [comment]
We could run `SELECT COUNT(*) FROM tasks`, which would serve dual purposes of testing the database connection and confirming the database is provisioned with tasks.

**Comment by divergentdave** [comment]
Should we check if `SELECT now()` is close to the local clock's time at startup as part of readiness checks? Clock skew could cause issues with leases, rejection of uploaded reports, and eager scheduling of aggregation jobs. If each worker checked its time against the database, we could hopefully catch glaring issues earlier.

If we don't want to gate on clock skew, perhaps processes should check their skew versus the database server periodically, and expose it as a gauge metric.

**Comment by tgeoghegan** [comment]
#323 added endpoints to the `aggregator` component for startup and health probes. Some more improvements we could make:

- expose health checks on all the Janus components
- expose health checks on a different port than the rest of the API so that we can avoid exposing healthz endpoints to the Kubernetes service that is wired up to external ingress

**Comment by BranLwyd** [comment]
> expose health checks on a different port than the rest of the API so that we can avoid exposing healthz endpoints to the Kubernetes service that is wired up to external ingress

Thinking about this a little more, we might be able to avoid exposing `/healthz` endpoints to the Internet if some higher-level routing component allows us to not route certain paths -- that would be another way to achieve the same goal.

**Comment by divergentdave** [comment]
I looked into this a bit, and the preferred method appears to involve running a deployment of `k8s.gcr.io/defaultbackend-amd64`, and adding rules to the ingress that route `/healthz` etc. to it. The container combines a static file server with an empty directory, so that it returns 404s for every request.

I think I'd prefer moving `/healthz` to another port. It appears that our load balancer health checks also support selecting different ports, so this would be the cleanest solution.

**Comment by tgeoghegan** [comment]
FWIW we already serve metrics scrapes from a separate port so one more port for healthz doesn't seem too bad to me.

**Comment by tgeoghegan** [comment]
I think we have accomplished everything listed in this ticket, so I'm going to close it. Please re-open if there's still something valuable tracked here.
