### ISSUE TITLE
Collector library

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#393]
Currently, writing a collector with Janus requires lots of plumbing code, between an HTTP client, Janus's message serialization and deserialization, HPKE decryption, VDAF aggregate share parsing, and unsharding. We should write a library that encapsulates all this, and encodes the DAP semantics regarding the HTTP responses.

**Comment by tgeoghegan** [comment]
We should make sure this collector library uses `janus_core::retries` to retry requests appropriately.

**Comment by branlwyd** [comment]
SGTM; part of this work should update our test container implementation to use this collector.

(There are a number of tests that effectively implement a collector, too -- we should consider migrating those tests to use the "official" collector library as well.)
