### ISSUE TITLE
BYO cryptography primitives for `janus_client`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#436]
Over in `libprio-rs`, we did some work to allow clients to bring their own cryptography primitive implementations instead of the ones crate `prio` uses by default. We might want to do the same thing in `janus_client`, assuming we can figure out a reasonable way to plumb (for instance) a client's PRG down into `prio`.

Relevant items in `libprio-rs`:
https://github.com/divviup/libprio-rs/issues/241
https://github.com/divviup/libprio-rs/pull/267
https://github.com/divviup/libprio-rs/pull/272

**Comment by branlwyd** [comment]
SGTM, as long as there is a default selection for the cryptographic primitives to keep things easy for folks that don't care too much which underlying implementation they get. I suppose this would likely be configured by a crate feature.

We might also wait until there is someone who wants this.

**Comment by divergentdave** [comment]
`janus_client` is generic over VDAF implementations, so alternative XOF implementations can be swapped in as needed. However, we do not provide a pluggable cryptography provider interface for the HPKE encryption. Mozilla is the primary user with strict cryptography library requirements, and they are currently using libprio-rs with their own XOF implementation, but not using `janus_client`, and doing message assembly and HPKE encryption in their own client code.
