### ISSUE TITLE
Store uploaded reports unencrypted

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#442]
Janus stores uploaded report shares in the database encrypted under either aggregator's HPKE public key. I think we should store report shares unencrypted because HPKE encryption is meant to protect messages in flight, so using it to protect data at rest feels like a mistake. It means we have to keep HPKE private keys around not just for as long as we might receive messages encrypted to that key, but as long as we might want to process stored reports encrypted to that key.

Further I think having the report shares in the clear would make it easier for us as developers and operators to investigate problems. Right now, if I want to look at an uploaded report to help someone debug, I have to go fetch the report out of the DB, then fetch the HPKE private key out of k8s secrets, then wire up some code to do the decryption. So nothing actually stops me from decrypting reports except a little extra toil, so I say: why not store the reports in plaintext?

Even if we do this, the leader still has to store the helper's share encrypted, because of course the leader doesn't have the helper's HPKE private key. However if, as we have long expected, DAP changes to mandate direct uploads to the helper and leader, then both aggregators could store unencrypted report shares.

**Comment by branlwyd** [comment]
👍🏻 SGTM.

We might eventually _choose_ to encrypt our report shares as part of a strategy to protect against insider threat (e.g. prevent a rogue operator from leaking report shares out to our co-aggregator). But at the current point, this would be a significant step forward in our security stance, and a realistic insider-threat strategy would require many more changes than this. (and, as you pointed out, we would probably not want to use HPKE encryption for encryption-at-rest -- so decrypting the incoming report share is just one step along the way to "properly" encrypting them)

**Comment by tgeoghegan** [comment]
This change would require changes to the DB schema, so I think we should lump this in with the [draft-02](https://github.com/divviup/janus/milestone/1) changes since that will likely require deploying a new instance of Janus and its database anyway.
