### ISSUE TITLE
`janus_core::message::{Time,Duration}` should be used only for message serialization/deserialization

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#445]
The `janus_core::message::{Time,Duration}` types are currently used for two purposes:
* DAP message serialization/deserialization.
* Representation of times/durations in various places throughout the codebase, such as configurations for various jobs.

Using our `Time`/`Duration` types for DAP message serialization/deserialization makes sense -- that is the purpose of those types.

OTOH, we should not use our `Time`/`Duration` for e.g. internally representing a duration of time in configurations or when performing time-based calculations:
* Doing so leads to us writing our own time math, which can be surprisingly error-prone.
* In the long run, DAP may move away from the need to represent timestamps or durations of time at all. It would be unfortunate if we were still using `Time`/`Duration` as a generic time/duration type at that point -- I suppose we'd end up having our own custom types for times & durations.

My suggestion would be that our internal `Time`/`Duration` types be used only "at the edge" -- converted from a standard representation of times/durations into the message types, just before serialization. For other purposes, we should use the appropriate types from the `chrono` crate, as we already do in some instances throughout our codebase.

(I think this same argument would apply to the `janus_core::message::Interval` type, except I'm not sure we have any "bad" usages in our codebase currently.)

**Comment by inahga** [comment]
We have a few examples of this still outstanding, but don't really need to address this proactively. We can pull this out into the style guide and address it over time.
