### ISSUE TITLE
Verify that collect requests cannot collect overlapping batch intervals

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#470]
See https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/277

I think maybe we already implement this in Janus.

**Comment by branlwyd** [comment]
I think we implement this too, but we should certainly double-check.

**Comment by tgeoghegan** [comment]
The checks we have in [`janus_server::aggregate_share::validate_batch_lifetime_for_collect`](https://github.com/divviup/janus/blob/d38cd7b0f7fe405a9506fcd354336cd2a19965d8/janus_server/src/aggregator/aggregate_share.rs#L454) do implement all the conditions required by [DAP-02](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.5.6), except that we don't return the correct problem types.

**Comment by tgeoghegan** [comment]
#586 mostly resolves this, except that `batchOverlap` is only checked in `collect_job_driver` but not while handling a `CollectReq`.
