### ISSUE TITLE
Revisit request authentication

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#472]
draft-ietf-ppm-dap-02 no longer requires the DAP-Auth-Token:

https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/293
https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/305

DAP-Auth-Token isn't forbidden by the new text, so we could leave that support in for backward compatibility with other DAP implementations, but we should look into implementing more secure authentication schemes for Divvi Up, perhaps leaning on managed identity offerings.

**Comment by tgeoghegan** [comment]
I think we will not make changes here as part of our DAP-02 implementation, since this touches on some bigger questions about subscriber management and the Divvi Up control plane. Removing this from the draft-ietf-ppm-dap-02 milestone.

**Comment by tgeoghegan** [comment]
In the future, we might implement more sophisticated authz -- for instance, issue tokens that are only permitted to exercise either the aggregation job or collection job sub-protocols -- but I think we have everything we need in place for the initial production deployment(s) of Divvi Up.

@branlwyd @divergentdave Is there anything else you think we should do w.r.t. request authentication? At most I think we might want to put a version into the bearer tokens we generate, which might make it easier to migrate to more sophisticated schemes in the future, but I'm not sure that's necessary.

**Comment by branlwyd** [comment]
I think we are fine with a bearer token. I wouldn't object to adding a version, but I don't think it's strictly necessary -- presumably any authentication token will have enough unguessable material that it is overwhelmingly unlikely that a valid auth token for one scheme is also valid in another scheme. (or, to think of it another way, a token from one scheme being valid in another scheme had better not be any more likely than a random string of bytes being valid in that scheme) OTOH, including a version would make the hypothetical code to parse multiple versions of tokens much simpler. A nice-to-have but not a requirement.

**Comment by divergentdave** [comment]
We should probably use a different header name when we change to a different authentication scheme, be it `Authorization` or something else. If that's the case, then I think it's fine to continue using `DAP-Auth-Token` with no version number structure in its value.

**Comment by tgeoghegan** [comment]
Following discussion in Slack: we're going to migrate to using proper bearer tokens. The primary motivation here is consistency across our API surfaces. To ease migration (for instance with Daphne), we'll examine both the `DAP-Auth-Token` and `Authorization` headers for some period and then cut over to exclusively honoring bearer tokens. #1300 tracks deprecating `DAP-Auth-Token`.

**Comment by tgeoghegan** [comment]
This ends up being kind of tricky. It's not too hard to teach `janus_aggregator` to accept either `Authorization: Bearer <token>` or `DAP-Auth-Token: <token>`, preferring the former, when handling aggregation job, collection or aggregate share requests. However we also want Janus' various components to start using proper bearer tokens when they are acting as an HTTP client, if the HTTP server expects that. But a Janus leader might be talking to helper run by an older Janus that only accepts `DAP-Auth-Token`, or by Daphne. I think that means we have to add a field to the `Task` structure (and a corresponding column to the `tasks` table) to indicate what authentication mode the helper expects. In turn, that means that the aggregator API and I think `divviup-api` need a way to indicate what authentication mode the helper uses for a task.

To keep review manageable, I'm going to stage this in multiple changes:

- [ ] Janus will start accepting either header when it acts as an HTTP server
- [ ] `janus_collector` and the `collect` binary will add an option to use one or the other auth mode (defaulting to bearer token)
- [ ] Schema etc. changes so we can track auth mode per-task
- [ ] Plumb auth mode through task creation in aggregator API and divviup-api

**Comment by tgeoghegan** [comment]
Applying the `byohelper` label here: the BYOHelper + self-service task provisioning work involves a bunch of tweaks to the aggregator API and `divviup-api`'s usage of it. That provides a great opportunity to switch the default behavior for new task generation from minting `DAP-Auth-Token` tokens to instead using RFC 6750 bearer tokens.

**Comment by tgeoghegan** [comment]
#1548 and the corresponding divviup-api change is the last thing I had in mind here, so closing this issue.
