### ISSUE TITLE
Adopt draft-irtf-cfrg-vdaf-03

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#473]
draft-ietf-ppm-dap-02 uses vdaf-03. We need to:

- [ ] take `prio` 0.9.x
- [ ] deal with the new public share parameter (including incorporating it into HPKE info strings)

https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/296
https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/307

**Comment by divergentdave** [comment]
This depends on #469 now (so we can feed report_count to num_measurements at the collector)
