### ISSUE TITLE
Run `cargo publish --dry-run` in CI

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#484]
In https://github.com/divviup/janus/pull/483, @divergentdave wisely did a dry run of crate publishing before bumping versions. We should do that automatically for every PR in `ci-build.yml`.

**Comment by branlwyd** [comment]
I think if we need to mark it `continue-on-error`, it's probably not providing too much value -- I guess it would start to break the first time we made a breaking change to `janus_core`, then stay broken until we published the next version.

Maybe we should instead do this in our publish-new-version CI jobs (`publish-crates.yml`)? Of course, the next step for that CI job would be to publish without `--dry-run`, so I'm not sure we gain a lot.

**Comment by tgeoghegan** [comment]
Given the arguments above, I don't think it makes sense to do anything here. Closing.
