### ISSUE TITLE
Release actions for containers, SQL schema stomp on "latest"

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#507]
We now release Janus from multiple release branches. The actions for publishing the SQL schema file and the Docker containers posts artifacts versioned by the git tag, but also "latest". So if we did a release from `main`, and then a release from `release/0.1`, then the "latest" version of those artifacts would be the one from the tip `release/0.1`, and it's not clear that we want that behavior.

**Comment by branlwyd** [comment]
I think we want to not use, and ideally not even publish (though I think it may be applied automatically?), a `latest` tag.

Maybe what we want is a tag like `0.1` that points to the latest `0.1.x` release? (and an eventual `0.2` tag that points to the latest `0.2.x` release, etc). Then a release `0.1.12` could be tagged with both `0.1` & `0.1.12` tags.

**Comment by divergentdave** [comment]
I cleaned up the `latest` tags from both GAR repositories. With that, I think we can close this issue.
