### ISSUE TITLE
`janus_cli provision-tasks` should generate the aggregator's HPKE config and private key

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#528]
`janus_cli provision-tasks` expects to be passed a file containing the YAML encoding of the tasks to provision into the Janus instance's database. This includes an HPKE configuration and private key for the aggregator to use, so the operator has to generate an HPKE config and encode it correctly. The tool should support generating the HPKE parameters if they are not present in the YAML task.

**Comment by branlwyd** [comment]
👍🏻, but at least for the collector HPKE config, it's plausible we should instead add support to make it easier to specify the collector HPKE config -- I suspect it will be very common that we are told the correct values to use there.

For values our aggregator "owns" like the aggregator private key/aggregator HPKE config, (optional) generation makes sense.

**Comment by tgeoghegan** [comment]
Good point -- I've retitled to make it clear this is about the aggregator's own HPKE bits.
