### ISSUE TITLE
Adopt `cargo` workspace improvements in Rust 1.64

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#584]
[Rust 1.64](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds) brings some `cargo` improvements for sharing values like crate version, dependencies, MSRV and others between member crates of a workspace. We should move Janus' MSRV to 1.64 and use those features, which will make version bump PRs like #583 simpler.

**Comment by tgeoghegan** [comment]
Using the shared dependencies is likely blocked on [dependabot support](https://github.com/dependabot/dependabot-core/issues/5315).

**Comment by divergentdave** [comment]
#640 did this for our main branch. Dependabot support has landed in the meantime.

**Comment by branlwyd** [comment]
Is there any additional work to be done for this issue? So far we have pulled workspace declarations (crate version, license, etc) out to the workspace-level `Cargo.toml`, and moved a few sensible dependency declarations out too.

I think we probably won't bump the `0.1` branch to a >= 1.64 MSRV, so this issue doesn't apply to that branch.

We can move additional dependencies out as it makes sense to do so, but I think that is not worth keeping this issue open. I'm going to close this issue out, if there are important bits worthy of continued tracking, please reopen w/ an explanation.
