### ISSUE TITLE
Adopt PostgreSQL 15

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#646]
PostgreSQL 15 was released today: https://www.postgresql.org/about/news/postgresql-15-released-2526/

We should consider adopting it into the next major version of Janus, once possible.

We'll need at least the following before we can realistically update:
* PostgreSQL 15 containers (used for unit & integration/interop testing)
* Support from GCP for PostgreSQL 15 (used for non-ephemeral deployments)

We should also evaluate that we do not regress due to the upgrade; I think once our tests are running with the new version of Postgres, they will provide a sufficient level of initial confidence.

**Comment by branlwyd** [comment]
Postgres 15 containers are now available as `postgres:15-alpine`. Still waiting on support from GCP before we consider updating.

**Comment by divergentdave** [comment]
Postgres 15 has hit GA in Cloud SQL.
https://cloud.google.com/sql/docs/postgres/release-notes#May_24_2023

**Comment by branlwyd** [comment]
(I believe the only work remaining to to choose to use Postgres 15 when we release & deploy a 0.6 Janus version; leaving this issue open to track that work.)

**Comment by tgeoghegan** [comment]
Divvi Up has deployed a few different instances of Janus 0.6.0 on Postgres 15. AFAICT they are handling reports happily, so I don't believe any further action is necessary in this project.
