### ISSUE TITLE
Add metrics to aggregation job creator

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#680]
Currently, the aggregation job creator does not export metrics.

We should export metrics on things like aggregation job creation rate, etc. Augmenting existing log lines with a metric would be a good starting point.

Fell out of discussion in https://github.com/divviup/janus/pull/658.

**Comment by divergentdave** [comment]
We now have two histograms in the aggregation job creator, one for the time it takes to update tasks, and one for the time it takes to create aggregation jobs for a task. The latter gives us aggregation job creation rate (by taking `rate()` of the associated `_sum` counter). We have good coverage of `error!` log lines via status labels on the histograms. I'm going to close this as complete, as we've got a good foundation in place now.
