### ISSUE TITLE
DAP-03: unrecognizedTask should use 400 Bad Request

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#705]
The next draft of the DAP spec will remove language specifying 404 Not Found for the `urn:ietf:params:ppm:dap:error:unrecognizedTask` error. Instead, we should respond with "400 Bad Request" for these errors.

**Comment by tgeoghegan** [comment]
I don't know that I agree. The specification should avoid being more specific than HTTP 400 or 500 per [RFC 9205](https://www.rfc-editor.org/rfc/rfc9205.html#name-using-http-status-codes), but an implementation like Janus is free to use a more specific error code in the 400 range, and for this case, 404 feels more appropriate and helpful to clients than a generic Bad Request.

**Comment by divergentdave** [comment]
There's a new sentence in [this paragraph in section 3.2](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-3.2-6) that says 'abort' "implies HTTP status code 400 Bad Request unless explicitly specified otherwise." I agree it would be better if the spec were flexible within 4xx/5xx categories.

**Comment by tgeoghegan** [comment]
The good news is that we can still change the protocol text for DAP-03!

**Comment by branlwyd** [comment]
I agree the specification text here should be more flexible; I'm going to hold off on implementing this change for now.
