### ISSUE TITLE
Documentation about how to deploy janus

### ISSUE THREAD

**Issue by MxmUrw** [divviup/janus#718]
For our [dspa-project](https://github.com/dpsa-project/overview), we need to run a janus instance in order to be able to test our type and pipeline.

It seems that setting up a janus deployment is not trivial, and I cannot find enough documentation to figure out the process. The end-to-end test in `interop_binaries/tests` has a very test-specific flavor, and it seems like a proper production (or even testing) deployment would look very different.

It could be that this is exactly the purpose of [daphne](https://github.com/cloudflare/daphne) (I just saw about it), but from the README it remains unclear to me what the exact relationship between daphne and janus is (both just say they are "implementations of DAP").

My current main goal is to setup such a testing environment, and I think I should continue at (https://github.com/cloudflare/daphne/issues/124). But it seems that it would be useful if there existed a description of how janus is supposed to be deployed (or the various options therefor).

**Comment by MxmUrw** [comment]
I can try to ask directly, then it's probably faster to answer:

1. Is the following correct? Each (of the two) aggregation servers consists of:
   - a postgres database
   - four running janus processes (`aggregator`, `aggregation_job_creator`, `aggregation_job_driver`, `collect_job_driver`)

2. It seems that the collector and the clients only communicate with the `aggregator` process. The others are background processes that just need to be started once and then do their work (as they read from the database) automatically, correct?

**Comment by branlwyd** [comment]
The above is correct (including the edit).

**Comment by divergentdave** [comment]
I started work on configuration for `docker-compose` in #806.

**Comment by MxmUrw** [comment]
I think this issue can be closed now that this [DEPLOYING.md](https://github.com/divviup/janus/blob/main/docs/DEPLOYING.md) is available.
