### ISSUE TITLE
Attributing costs to DAP tasks (metering)

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#847]
We need to measure or at least estimate how much it is costing us to run aggregations for some DAP task so that we can then bill subscribers accurately (for those subscribers that we bill). As Janus is multitenant (at least inasmuch as one database contains multiple tasks belonging to multiple subscribers), we will probably need to measure what proportion of compute, networking, storage and other costs are used for each task.

**Comment by tgeoghegan** [comment]
At this point, we've got [detailed per-report cost estimates](https://docs.google.com/document/d/1twTv_DYujRMhJy8wLbhBh9bIUIpom_mrJqiyKt3AgoY/edit#heading=h.v6nmoijcluzn) worked up by David, and [the aggregator API can serve up metrics on how many reports have been aggregated per-task](https://github.com/divviup/janus/blob/43eca9bb3f91592c90e7c2d713cb0af3616925ff/aggregator_api/src/lib.rs#L951). Do we need anything else to be able to bill subscribers, like maybe representing costs on a per-month basis? Or does this suffice for the current production readiness goal?

**Comment by tgeoghegan** [comment]
In that case I think we can punt this issue out of the "Production readiness" milestone, as it doesn't sound like further work here is a blocker.

**Comment by tgeoghegan** [comment]
Our current task utilization metrics work by counting rows in e.g. the `client_reports` table, but don't account for garbage collection. We need to account for that before we deploy anything that uses task metrics for billing decisions.

**Comment by inahga** [comment]
We have counters for report uploads and helper-side successful aggregation, which for now are sufficient for deriving data for metering and billing.
