### ISSUE TITLE
Janus does not work on M1 Macs

### ISSUE THREAD

**Issue by simon-friedberger** [divviup/janus#948]
ARM is currently not support by Janus so M1 Macs cannot be used for development.
I was looking for a way to get around that.

I have set up podman with qemu in such a way that images for other architectures can be run.

Specifically, I have done
```
podman machine init --cpus=4 --memory=8192 -v $HOME:$HOME
podman machine ssh
sudo rpm-ostree install qemu-user-static
sudo systemctl reboot
```
testing that it works with e.g.
```
podman run --rm -it docker.io/amd64/alpine 
```

At this point the janus build still fails. So I made a few changes to replace calls to docker with calls to podman and specifying `--arch=aarm64` (docker doesn't have that argument). That makes the build work.

`cargo test` is still failing when trying to create the ephemeral DB. I probably won't pursue this further but maybe this is useful information to somebody. At least it's possible (if a bit slow) to build.

**Comment by tgeoghegan** [comment]
I don't think we should commit to supporting any target unless we can run our CI on it. I think we can just add latest macOS to our test matrix, but AFAICT Apple Silicon VMs are not yet available in GitHub Actions (https://github.com/actions/runner-images/issues/2187, https://github.com/github/roadmap/issues/528). The [prior art](https://langui.sh/2023/01/15/ephemeral-gha-m1-runners-with-cidermill/) I'm aware of for GHA on Apple Silicon involves running your own fleet of runners, which is not something I think we should commit to doing.

**Comment by inahga** [comment]
I've had success on my M3 Macbook with developing Janus both locally and containerized. @simon-friedberger, let me know if you're still having problems.

Note that I use [Colima](https://github.com/abiosoft/colima) as my container VM, but this is largely a matter of taste.
