### ISSUE TITLE
Garbage collection: port helper GC to 0.2?

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#962]
A potential upcoming integration would require us to run a DAP-02 deployment as the Helper. Currently, GC is only implemented for Leader tasks in the relevant version of Janus (`0.2`). Should we commit to this integration, we need to backport helper GC to Janus `0.2`.

Doing so would require backporting the `client_timestamp_interval` functionality. The DU team discussed internally and we decided that we likely do **not** need to provide a backfilling tool or process for `client_timestamp_interval`; this significantly reduces the effort required for development, at the risk that someone still using the `0.2` branch may not be able to GC preexisting tasks properly once this functionality is released.

**Comment by tgeoghegan** [comment]
I think this issue is obsolete since we abandoned the `release/0.2` branch. Please re-open if I'm wrong.
