### ISSUE TITLE
Create Divvi Up-specific client library.

### ISSUE THREAD

**Issue by branlwyd** [divviup/janus#985]
Currently, the `janus_client` crate can be used as a generic DAP client, while the `janus_collector` crate can be used as a generic DAP collector.

To reduce confusion among users due to the name, and to allow Divvi Up-specific functionality to be added, we should publish a new library named `divviup_rs` (with the crate being named perhaps `divviup`).

The initial version of this crate would likely just re-export `janus_client` symbols. We might eventually add additional Divvi Up-specific functionality (i.e. hard-coding/defaulting of DAP endpoint names, types which specialize generics for Divvi Up-specific use-cases, control plane operations).

We should consider whether it makes sense to provide DAP collector functionality in `divviup_rs` as well.

**Comment by inahga** [comment]
We're not going to do this at this time. In other client libraries such as divviup-ts and divviup-android, we've eschewed any hard dependencies on Divvi Up.

Clients with some hard-coding may still be useful as we built out the divviup-api control plane, but at this time it's not necessary.
